### PR TITLE
Prioritize failures in zipWith

### LINKED ISSUE #600: `Stream#zip` does not prioritize stream failures
Reproduction:
```scala
import scalaz.zio._, scalaz.zio.stream._
val RTS = new DefaultRuntime {}

RTS.unsafeRun {
  for {
    q <- Queue.unbounded[Int].map(Stream.fromQueue)
    _ <- q.zip(Stream.fail(new Exception)).run(Sink.collect[(Int, Nothing)])
  } yield ()
}
```

This hangs instead of failing.

### PR DESCRIPTION
**Pull request by iravid**
Fixes #600

### CODE REVIEW

File: core/shared/src/main/scala/scalaz/zio/stream/Stream.scala [hunk 1]
```diff
@@ -564,20 +564,31 @@ trait Stream[-R, +E, +A] extends Serializable { self =>
...
-                f(left, right) match {
-                  case None => IO.succeed(s)
-                  case Some(c) =>
-                    g(s, c).flatMap { s =>
-                      if (cont(s)) loop(left.isEmpty, right.isEmpty, q1, q2, s)
-                      else IO.succeed(s)
-                    }
-                }
-            }
+            val takeLeft: ZIO[R2, E2, Option[A]]  = if (leftDone) IO.succeed(None) else Take.option(q1.take)
```
Comment (iravid) [inline core/shared/src/main/scala/scalaz/zio/stream/Stream.scala]: I had to annotate these lines explictly, otherwise this is inferred as `ZIO[Any, E2, Option[A]]` and line 584 results in an error that `Any` is required but `R2` is found.

I haven't investigated why the narrowing fails, but this might be another candidate for inference improvements before 1.0.
