### PR TITLE
Don't supervise finalizers

### LINKED ISSUE #288: .supervised on failing computation causes deadlock
Example:

```scala
import scalaz.zio.{IO, RTS}

object App extends App {
  println("With termination")
  new RTS{}.unsafeRun(IO.sync(throw new RuntimeException("")).supervised)

  println("With fail")
  new RTS{}.unsafeRun(IO.syncThrowable(throw new RuntimeException("")).supervised)
}
```

Expected: Exceptions

Actual: Hangs

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Closes #288 

During supervision, finalizers run in separate fibers, so that defects in them can be captured. However, they shouldn't be supervised themselves! We can avoid that forking directly rather than going through the whole `IO.Fork` route.

### CODE REVIEW

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 1]
```diff
@@ -279,7 +279,7 @@ private object RTS {
         // (reverse chronological).
         stack.pop() match {
           case f0: Finalizer =>
-            val f: IO[Nothing, Option[List[Throwable]]] = f0.finalizer.run.map(collectDefect)
+            val f: IO[Nothing, Option[List[Throwable]]] = fork(f0.finalizer, _ => IO.unit).observe.map(collectDefect)
```
Comment (regiskuckaertz) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: I had another version that was much simpler:
```scala
fork(f0.finalizer, accumFailures)
```
which allowed me to get rid of `collectDefect` and `zipFailures`; however, the unhandled errors handler action is submitted on the thread pool, so there is no guarantee of ordering.

Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Exactly, and finalizers must be linearly ordered.
