### PR TITLE
Semaphores revisited

### LINKED ISSUE #293: Semaphore broken?
Example:

```scala
import scalaz.zio._

object App extends App {
  new RTS{}.unsafeRun {
    for {
      s <- Semaphore(1).peek(_.acquire)
      _ <- s.release.fork
      _ <- s.acquire
    } yield ()
  }
}
```

Blocks forever. Removing `.fork` from `release` makes it work.

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Closes #293 

I feel this version is more in line with the style we use elsewhere and also much easier to read. And I think now I understand `Promise.bracket`, even though I don't really need its full power (i.e. the `release` action).

### CODE REVIEW

**Comment by jdegoes** [comment]
You will probably need the release action in Promise.bracket so you can remove the promise from the Semaphore state. Because if someone calls acquire but needs to wait, then it gets interrupted, that needs to be cleaned up.

File: core/shared/src/main/scala/scalaz/zio/Semaphore.scala [hunk 1]
```diff
@@ -4,112 +4,69 @@
...
+  final def acquireN(requested: Long): IO[Nothing, Unit] = {
+    val acquire: (Promise[Nothing, Unit], State) => (IO[Nothing, Boolean], State) = {
+      case (p, Right(n)) if n >= requested => p.complete(()) -> Right(n - requested)
+      case (p, Right(n))                   => IO.now(false)  -> Left(IQueue(p -> (requested - n)))
+      case (p, Left(q))                    => IO.now(false)  -> Left(q.enqueue(p -> requested))
+    }
+
+    val release: (Boolean, Promise[Nothing, Unit]) => IO[Nothing, Unit] = {
+      case (_, p) =>
+        p.poll.void <> state.update {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: `p.poll.void` can have no effect, why use it?

File: core/shared/src/main/scala/scalaz/zio/Semaphore.scala [hunk 2]
```diff
@@ -4,112 +4,69 @@
...
+          case Left(q) => Left(q.filterNot(_._1 == p))
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: Yes, this will help ensure the promise is removed. I'd use `eq` instead of `==`.

File: core/jvm/src/test/scala/scalaz/zio/SemaphoreSpec.scala [hunk 3]
```diff
@@ -43,6 +44,15 @@ class SemaphoreSpec extends AbstractRTSSpec {
...
 
+  def e5 = {
+    val n = 1L
+    unsafeRun(for {
+      s <- Semaphore(n).peek(_.acquire)
+      _ <- s.release.fork
+      _ <- s.acquire
+    } yield () must_=== (()))
+  }
+
```
Comment (jdegoes) [inline core/jvm/src/test/scala/scalaz/zio/SemaphoreSpec.scala]: We may want to add one crazy test in here that does stuff from a lot of fibers. The above one is certainly helpful.

**Comment by jdegoes** [comment]
@regiskuckaertz Huge improvement! Way less code and easier to understand. I'm must more confident in its correctness. Would be good to add a test for the case of an interrupted acquire.

File: core/shared/src/main/scala/scalaz/zio/Semaphore.scala (hunk 1 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: I was going to say the promise can only be completed if it is taken out of the queue, but interruption can occur between the `complete` call and the moment the queue is updated in the ref.

File: core/shared/src/main/scala/scalaz/zio/Semaphore.scala (hunk 2 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: We'd have to make `Promise` a subtype of `AnyRef`, which sounds reasonable anyway?

File: core/shared/src/main/scala/scalaz/zio/Semaphore.scala (hunk 1 above)
Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: I still don't understand. I think if you delete `p.poll.void <>`, the meaning of this code won't change.

File: core/shared/src/main/scala/scalaz/zio/Semaphore.scala (hunk 2 above)
Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: Nah, let's just leave it.

File: core/shared/src/main/scala/scalaz/zio/Semaphore.scala (hunk 1 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: In the happy path, the promise given to `release` is already completed (that is part of `Promise.bracket`, specifically the `p.get`), which can only happen if it is not in the queue (that is imposed by the definition of `acquireN`/`releaseN`).

Actually I take back my previous comment, because `Promise.bracket` guarantees atomicity, _if_ the promise is completed we can deduce that it is not in the queue anymore! So, with `p.poll.void` we avoid the extra state update if the promise has already been removed from the queue.

Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: What does `p.poll` do? AFAIK, it doesn't do anything, it just peeks in the promise and returns the value as a result, which is then thrown away with `void`. Am I missing something?

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: In this case, I'm only interested to know whether the promise is complete or not: and `poll` fails in the latter case, which means I can run provide an alternative action (update the state) with the `<>` combinator.

Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: Ah, OK, I see now that `poll` fails with `Unit` if the result is not available. Unfortunately there's a race condition—it's possible the promise will be completed between `p.poll.void` and `state.update`. Because other threads may be concurrently modifying state (releasing, which could trigger promise completion). If there's a race condition then we should always update the state. Or am I missing something else?

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: The `release` action is inside a finaliser (via `io.ensuring(...)`), which means it is not interruptible and so this should be fine. Amirite?

Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: It's not interruptible, however, the state of the promise can still change during the execution of the action. `Promise.bracket` provides no guarantees on concurrent access, only a guarantee if acquire succeed, that release will succeed, regardless of interruption.

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Semaphore.scala]: That is correct 😞 Thanks for the explanation!
