### PR TITLE
Get rid of `Race` primitive

### LINKED ISSUE #320: Supervision is broken with race
Example:

```scala
import scalaz.zio.console._
import scalaz.zio._
import scala.concurrent.duration._

object App extends scala.App {
  new RTS{}.unsafeRun(for {
    f <- (IO.never race IO.never).supervised(fs => putStrLn(s"child fibers: ${fs.size}")).fork
    _ <- IO.sleep(1.second)
    _ <- f.interrupt
  } yield ())
}
```

Expected:
```
child fibers: 2
```

Actual:
```
child fibers: 0
```

### LINKED ISSUE #324: Eliminate `raceWith` as primitive operation
Draft of overall approach:

```scala
sealed trait Race[+E, +A, +B] {
  final def over: Boolean = this match {
    case LeftDone(ExitResult.Completed(_)) => true 
    case RightDone(ExitResult.Completed(_)) => true 
    case _ => false 
  }
  final def leftDone: Boolean = this match {
    case LeftDone(_) => true 
    case _ => false 
  }
  final def rightDone: Boolean = this match {
    case RightDone(_) => true 
    case _ => false 
  }
}
final case object Started extends Race[Nothing, Nothing, Nothing]
final case class LeftDone(value: ExitResult[E, A]) extends Race[E, A, B]
final case class RightDone(value: ExitResult[E, B]) extends Race[E, A, B]

def raceWith[E1 >: E, E2, B, C](that: IO[E1, B])(
  leftWins: (Fiber[E1, A], Fiber[E1, B]) => IO[E2, C],
  rightWins: (Fiber[E1, A], Fiber[E1, B]) => IO[E2, C]): IO[E2, C] = 
  for {
    fibers <- Ref[Option[(Fiber[E1, A], Fiber[E1, B])]](None)
    c      <- (for {
                t <- (for {
                       promise <- Promise.make[E2, C]
                       state   <- Ref[Race[E, A, B]](Started)
                       left    <- self.fork
                       right   <- that.fork
                       _       <- fibers.set(Some(left -> right))
                     } yield (state, promise, left, right)).uninterruptibly
                (state, promise, left, right) = t 
                _ <- IO.flatten(left.observe.flatMap(v => state.modify(race => 
                       (if (!race.over && (v.isCompleted || race.rightDone)) leftWins(left, right).run.flatMap(promise.done(_)).void else IO.unit) -> LeftDone(v)))).fork
                _ <- IO.flatten(right.observe.flatMap(v => state.modify(race =>
                       (if (!race.over && (v.isCompleted || race.leftDone)) rightWins(left, right).run.flatMap(promise.done(_)).void else IO.unit) -> RightDone(v)))).fork
                c <- promise.get
              } yield c).ensuring(fibers.get(_.fold(IO.unit)(t => t._1.zip(t._2).interrupt)))
  } yield c
```

/cc @regiskuckaertz

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Closes #324 

Closes #320

### CODE REVIEW

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 1]
```diff
@@ -913,6 +940,18 @@ object IO extends Serializable {
...
+  /**
+   * The moral equivalent of `if (p) exp`
+   */
+  final def when[E](b: Boolean, io: IO[E, Unit]): IO[E, Unit] =
+    if (b) io else IO.unit
+
+  /**
+   * The moral equivalent of `if (p) exp` when `p` has side-effects
+   */
+  final def whenM[E](b: IO[Nothing, Boolean], io: IO[E, Unit]): IO[E, Unit] =
```
Comment (kaishh) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: > final def when[E](b: Boolean, io: IO[E, Unit])

Suggestion: maybe this could have split argument lists for convenience?

`final def when[E](b: Boolean)(io: IO[E, Unit])`

Possibly with a partially applied class if inference is bad without it.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 2]
```diff
@@ -536,11 +558,7 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
   final def timeout[B](z: B)(f: A => B)(duration: Duration): IO[E, B] =
     self
       .map(f)
-      .attempt
-      .raceWith[E, Either[E, B], B, B](IO.now[B](z).delay(duration))(
-        (either: Either[E, B], right: Fiber[E, B]) => right.interrupt *> either.fold(IO.fail, IO.now),
-        (b: B, left: Fiber[E, Either[E, B]]) => left.interrupt *> IO.now(b)
-      )
+      .raceWith(IO.now[B](z).delay(duration))(_.join <* _.interrupt, _.join <* _.interrupt)
```
Comment (kaishh) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: This breaks `timeout of failure` test... Is there a way to make `upTo` fail the test instead of skipping in specs2?

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Oh, I did not see it. Of course it fails 🤦‍♂️

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Hmm, wait, that's normal. If the first fiber fails, we'll wait for the second one. That's part of the semantics of `raceWith`.

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Fixed, thanks 👍

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 3]
```diff
@@ -138,18 +138,8 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
-      {
-        case (Left(e), fiberb)  => fiberb.interrupt *> IO.fail[E1](e)
-        case (Right(a), fiberb) => IO.absolve[E1, B](fiberb.join).map((b: B) => f(a, b))
-      }, {
-        case (Left(e), fibera)  => fibera.interrupt *> IO.fail[E1](e)
-        case (Right(b), fibera) => IO.absolve[E1, A](fibera.join).map((a: A) => f(a, b))
-      }
-    )
-  }
+  final def parWith[E1 >: E, B, C](that: IO[E1, B])(f: (A, B) => C): IO[E1, C] =
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: In the event one side fails, `parWith` needs to interrupt the other side, so the minimum amount of computation is performed. That's why it's old implementation is so complex—this simplification is very elegant but unfortunately destroys that property.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 4]
```diff
@@ -173,16 +163,42 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
+
+    (for {
+      done  <- Promise.make[E2, C]
+      race  <- RefM[IO.Race](IO.Race.Started)
+      left  <- self.fork
+      right <- that.fork
+      _     <- left.observe.flatMap(arbiter(leftWins, left, right, race, done)).fork
+      _     <- right.observe.flatMap(arbiter(rightWins, right, left, race, done)).fork
+      c     <- done.get
+    } yield c).supervised
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: I don't think `supervised` works if the fiber is interrupted. We should probably fix that. If you fix that, this will be equivalent to the old way which used `ensuring` to make sure that if the parent is killed, the racing fibers are killed as well. 

Also in this method you can kind of see why we wanted `observe` (well, the old version, `onComplete`) to take a call back: because we turn right around and fork it because we just want to do something when observation happens. (But nonetheless, probably better to express it this way, it's more orthogonal, and we can always optimize RTS for this pattern.)

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 5]
```diff
@@ -173,16 +163,42 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
+  ): IO[E2, C] = {
+    def arbiter[E0, E1, A, B](
+      f: (Fiber[E0, A], Fiber[E1, B]) => IO[E2, C],
+      winner: Fiber[E0, A],
+      loser: Fiber[E1, B],
+      race: RefM[IO.Race],
+      done: Promise[E2, C]
+    )(res: ExitResult[E0, A]): IO[Nothing, _] =
+      race
+        .modify(
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: As far as I can see, you use `modify` but throw away the return value, so you may as well use `update` instead of `modify`.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 6]
```diff
@@ -173,16 +163,42 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
-    new IO.Race[E1, A1, B, C](self, that, finishLeft, finishRight)
+  )(
+    leftWins: (Fiber[E, A], Fiber[E1, B]) => IO[E2, C],
+    rightWins: (Fiber[E1, B], Fiber[E, A]) => IO[E2, C]
+  ): IO[E2, C] = {
+    def arbiter[E0, E1, A, B](
+      f: (Fiber[E0, A], Fiber[E1, B]) => IO[E2, C],
+      winner: Fiber[E0, A],
+      loser: Fiber[E1, B],
+      race: RefM[IO.Race],
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: I would strongly recommend we not use `RefM` here, because `RefM` is tremendously slower than `Ref`. It does make things simpler but at too high a cost for such a fundamental operation as `raceWith`.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 7]
```diff
@@ -537,9 +553,10 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
     self
       .map(f)
       .attempt
-      .raceWith[E, Either[E, B], B, B](IO.now[B](z).delay(duration))(
-        (either: Either[E, B], right: Fiber[E, B]) => right.interrupt *> either.fold(IO.fail, IO.now),
-        (b: B, left: Fiber[E, Either[E, B]]) => left.interrupt *> IO.now(b)
+      .raceWith(IO.now[B](z).delay(duration))(
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: While you're in here, can you change this so that if `self` is terminated, the action times out as well.

It strikes me that would be easier if we had an even more powerful `raceWith` operation that would call `leftDone` and then `rightDone` in some order and then could decide to do whatever with a promise and the fibers that are passed in (or maybe there's a better way to generalize it).

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 8]
```diff
@@ -686,14 +703,13 @@ object IO extends Serializable {
...
-    final val Terminate       = 14
-    final val Supervisor      = 15
-    final val Ensuring        = 16
+    final val Suspend         = 9
+    final val Uninterruptible = 10
+    final val Sleep           = 11
+    final val Supervise       = 12
+    final val Terminate       = 13
+    final val Supervisor      = 14
+    final val Ensuring        = 15
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: Nice to see these shrink! Also if you look at the PR, it's net negative! 🎉 🕺

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 9]
```diff
@@ -780,6 +787,25 @@ object IO extends Serializable {
...
+      case _                          => true
+    }
+
+    def next(succeeded: Boolean): Race = self match {
+      case Race.Started if !succeeded => Race.OtherFailed
+      case _                          => Race.Done
+    }
+  }
+
+  object Race {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: This needs to be package private, I think.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 10]
```diff
@@ -913,6 +939,18 @@ object IO extends Serializable {
...
+  /**
+   * The moral equivalent of `if (p) exp`
+   */
+  final def when[E](b: Boolean)(io: IO[E, Unit]): IO[E, Unit] =
+    if (b) io else IO.unit
+
+  /**
+   * The moral equivalent of `if (p) exp` when `p` has side-effects
+   */
+  final def whenM[E](b: IO[Nothing, Boolean])(io: IO[E, Unit]): IO[E, Unit] =
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: You could (should?) add syntax for these in the syntax module.

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 4 above)
Comment (kaishh) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: I'm fairly sure .supervised works on interruption, at least that's pretty much the only case I'm using it for.

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Yeah I think it works, see:
https://github.com/scalaz/scalaz-zio/blob/989ca743611c82357efcdaa3ff9249d64a01eec7/core/jvm/src/main/scala/scalaz/zio/RTS.scala#L542-L546
The supervisor is run as a finalizer.

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 3 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: If I supervise this action, then any failure will make the whole action fail, which will lead to `catchError` collecting the finalizers and run them, thereby killing all fibers. If this is incorrect _or_ supervision kills performance, I have another version that uses `parWith` and observes the fibers.

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 10 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Like this?
```
io.when(pred)
```
Then I may just add `io.when` directly. Somehow the opposite (`pred.when(io)`) feels weird.

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: ha no, only on `IO[E, Unit]`

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 3 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Such a conundrum 😅 The `raceWith` version looks as elegant imho, but I like the idea of having a separate `Fiber#parWith` (or `zipWithPar`, according to the decided terminology?)

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 6 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Done, also much cleaner with `Ref`, the only requirement was that the state be updated atomically and `race.modify` is perfect for that.

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 8 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: It says a lot about the expressiveness of ZIO 😍

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 7 above)
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: This one is trickier 🤠  If the `arbiter` function was provided by the caller, then we could implement both strategies, i.e. fail fast or fail last. For fail fast, it becomes:
```scala
def arbiterFast(f, winner, loser, race, done) = {
  case ExitResult.Completed(_) => f(winner, loser).map(done.done(_))
  case ExitResult.Failed(e, ts) => loser.interrupt *> IO.fail0(e, ts)
  case ExitResult.Terminated(ts) => loser.interrupt *> IO.terminate(ts)
}
```
It's ugly though, would require some massaging. With that:
```scala
def timeout[B](z: B)(f: A => B)(duration: Duration): IO[E, B] =
  (self.map(f) raceWith IO.now(z).delay(duration))(arbiterFast, _.join <* _.interrupt)
```

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 11]
```diff
@@ -534,13 +554,16 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
-      .attempt
-      .raceWith[E, Either[E, B], B, B](IO.now[B](z).delay(duration))(
-        (either: Either[E, B], right: Fiber[E, B]) => right.interrupt *> either.fold(IO.fail, IO.now),
-        (b: B, left: Fiber[E, Either[E, B]]) => left.interrupt *> IO.now(b)
-      )
+    IO.now(z).delay(duration).fork.flatMap { fiber =>
+      self
+        .map(f)
+        .attempt
+        .onTermination(_ => fiber.interrupt)
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: These are our desired semantics:

1. If `self` takes longer than `duration`, then `z` is chosen.
2. In all other cases, `self` is chosen as soon as possible.

I think we can do that with:

```scala
self.map(f).sandboxWith(io => 
  IO.absolve(IO.now(z).delay(duration) race io.attempt))
```

The sandboxing ensures that `self` will "win" the race whether it fails with some value, or terminates due to defect or interruption.

Does that seem correct to you?

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 12]
```diff
@@ -173,16 +170,39 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
+    def arbiter[E0, E1, A, B](
+      f: (Fiber[E0, A], Fiber[E1, B]) => IO[E2, C],
+      winner: Fiber[E0, A],
+      loser: Fiber[E1, B],
+      race: Ref[IO.Race],
+      done: Promise[E2, C]
+    )(res: ExitResult[E0, A]): IO[Nothing, _] =
+      race
+        .modify(r => r.won(res.succeeded) -> r.next(res.succeeded))
+        .flatMap(IO.when(_)(f(winner, loser).run.flatMap(done.done(_)).void))
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: This makes me want to add:

```scala
trait IO[+E, +A] {
  final def to(p: Promise[E, A]): IO[Nothing, Unit] = 
    self.run.flatMap(p.done(_)).void
}
```

And of course it makes me want to optimize `run`. 😄 

This looks great to me! It's very tricky to get this perfectly right.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 13]
```diff
@@ -139,16 +139,13 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
-    val s: IO[Nothing, Either[E1, A]] = self.attempt
-    s.raceWith[E1, Either[E1, A], Either[E1, B], C](that.attempt)(
-      {
-        case (Left(e), fiberb)  => fiberb.interrupt *> IO.fail[E1](e)
-        case (Right(a), fiberb) => IO.absolve[E1, B](fiberb.join).map((b: B) => f(a, b))
-      }, {
-        case (Left(e), fibera)  => fibera.interrupt *> IO.fail[E1](e)
-        case (Right(b), fibera) => IO.absolve[E1, A](fibera.join).map((a: A) => f(a, b))
+    def coordinate[A, B](f: (A, B) => C)(winner: Fiber[E1, A], loser: Fiber[E1, B]): IO[E1, C] =
+      winner.observe.flatMap {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: Looks good to me!

**Comment by regiskuckaertz** [comment]
There's a flakey test in `RefMSpec`, looking at it.

**Comment by ghostdogpr** [comment]
> There's a flakey test in `RefMSpec`, looking at it.

I had the same issue and addressed it in #342 https://github.com/scalaz/scalaz-zio/pull/342#discussion_r230576069

Should I submit a dedicated PR for it?

**Comment by regiskuckaertz** [comment]
@ghostdogpr fantastic ❤️ yes please, it feels like a separate issue.

**Comment by ghostdogpr** [comment]
@regiskuckaertz here it is https://github.com/scalaz/scalaz-zio/pull/343

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 14]
```diff
@@ -791,6 +795,25 @@ object IO extends Serializable {
     override def tag = Tags.Ensuring
   }
 
+  sealed abstract class Race private[zio] { self =>
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: We should move the `private[zio]` to the front, so the whole class is private, otherwise just the constructor will be private.

**Comment by jdegoes** [comment]
🎉 🎆 🕺

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 4 above)
Comment (kaishh) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Seems like it would be impossible to implement [`Concurrent.racePair`](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Concurrent.scala#L217) on top of `raceWith` if it's supervised, the loser fiber has to stay alive some more after it exits
