### PR TITLE
Fixes #868

### LINKED ISSUE #868: STM orElse method results in partially-rolled-back commits
I believe I have found an issue in STM pertaining to the use of `STM.orElse` that results in partially-rolled-back commits. From exploring in a debugger, I'm pretty sure the root cause of the issue is [here](https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/stm/STM.scala#L235), where, when an STM fails and triggers its `orElse` block, the *entire* current state of the journal is reset, rather than just resetting the portions of the journal that were modified by the failed STM. 

Am I misunderstanding the purpose of the `orElse` method? In its current form it seems like it is only usable as a top-level "this or that" for use just before actually executing a transaction, rather than a mechanism for graceful failure handling within composed transactions like I thought.

Here's a fairly minimal example that reproduces the issue:

```
val runtime = new DefaultRuntime {}

val ref1 = runtime.unsafeRun(TRef.makeCommit(0))
val ref2 = runtime.unsafeRun(TRef.makeCommit("msg"))

val action1 = STM.atomically {
  for {
    _ <- ref1.set(2)
    newVal <- ref1.get
    computedMsg <- STM.partial(throw new RuntimeException()).orElse(STM.succeed("newMsg"))
    _ <- ref2.set(computedMsg)
    newMsg <- ref2.get
  } yield (newVal, newMsg)
}

val a1res = runtime.unsafeRun(action1)
println(s"Result of running action 1: $a1res")

val action2 = STM.atomically {
  for {
    val1 <- ref1.get
    val2 <- ref2.get
  } yield (val1, val2)
}

val a2res = runtime.unsafeRun(action2)
println(s"Result of running action 2: $a2res")
```

Result of the above is:

```
Result of running action 1: (2,newMsg)
Result of running action 2: (0,newMsg)
```

However, with a small tweak to replace `orElse` with a try/catch, you get correct results:

```
val runtime = new DefaultRuntime {}

val ref1 = runtime.unsafeRun(TRef.makeCommit(0))
val ref2 = runtime.unsafeRun(TRef.makeCommit("msg"))

val action1 = STM.atomically {
  for {
    _ <- ref1.set(2)
    newVal <- ref1.get
    computedMsg <- STM.succeed(try {
      throw new RuntimeException()
    } catch {
      case _: Exception => "newMsg"
    })
    _ <- ref2.set(computedMsg)
    newMsg <- ref2.get
  } yield (newVal, newMsg)
}

val a1res = runtime.unsafeRun(action1)
println(s"Result of running action 1: $a1res")

val action2 = STM.atomically {
  for {
    val1 <- ref1.get
    val2 <- ref2.get
  } yield (val1, val2)
}

val a2res = runtime.unsafeRun(action2)
println(s"Result of running action 2: $a2res")
```
Result of the above is:

```
Result of running action 1: (2,newMsg)
Result of running action 2: (2,newMsg)
```

Which is the result I would expect from the above snippet.

### PR DESCRIPTION
**Pull request by jdegoes**
Mainly a fix for #868, as well as more precise handling of `suspend` in the newly optimized STM ("infinite bad luck" combined with unstable ref identities could lead to infinite accumulation).

### CODE REVIEW

File: core/shared/src/main/scala/scalaz/zio/stm/STM.scala [hunk 1]
```diff
@@ -395,77 +408,114 @@ object STM {
...
+    /**
+     * Performs a diff on the two journals, returning only the "new" entries.
+     */
+    final def diffJournals(oldJournal: Journal, newJournal: Journal): Journal = {
+      val diffJournal = new MutableMap[TRefId, Entry](newJournal.size)
+
+      diffJournal.putAll(newJournal)
+
+      newJournal.forEach { (key, _) =>
+        if (oldJournal.containsKey(key)) {
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/stm/STM.scala]: Is there no change of different values for the same key?

Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/stm/STM.scala]: I _think_ that for this purpose, we just care whether or not we knew about the existence of the entry, because if we knew it existed, then regardless of its value, we added it to the `todo` list of the references, and therefore don't need to consider it in the diff. Does that make sense?

Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/stm/STM.scala]: ^^^ @regiskuckaertz

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/stm/STM.scala]: ah yeah, I get it 👍
