### PR TITLE
Fix RefM race condition

### LINKED ISSUE #345: Intermittent failure in RefMSpec
Sometimes `modifyFold` test fails, sometimes it doesn't.

https://travis-ci.org/scalaz/scalaz-zio/jobs/450429126

### PR DESCRIPTION
**Pull request by ghostdogpr**
There is a race condition in `RefM.modify` that causes a test to fail randomly in other PRs.

This is due to `ref.set` being called after `modify` returns, so a subsequent `ref.get` doesn't always get the desired value. I moved it so that it's called before `modify` returns.

Closes #345

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
That's great 😍 How about threading `onDefect` inside `run` and saving one `redeem`?

**Comment by ghostdogpr** [comment]
@regiskuckaertz makes sense! I moved it.

**Comment by ghostdogpr** [comment]
Closes 345

File: core/shared/src/main/scala/scalaz/zio/RefM.scala [hunk 1]
```diff
@@ -66,15 +66,15 @@ object RefM extends Serializable {
     update: A => IO[Nothing, (B, A)],
     promise: Promise[Nothing, B]
   ) {
-    final def run(a: A): IO[List[Throwable], A] =
+    final def run(a: A, ref: Ref[A], onDefect: List[Throwable] => IO[Nothing, Unit]): IO[List[Throwable], Unit] =
       interrupted.get.flatMap {
-        case Some(ts) => IO.fail(ts)
+        case Some(ts) => onDefect(ts) *> IO.fail(ts)
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/RefM.scala]: I think this should just be `onDefect(ts)`, as previously we had (after reduction) 
```scala
IO.fail(ts).redeem(onDefect, _) : IO[Nothing, _]
```
The error channel is erased by `onDefect`.

Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/RefM.scala]: Oh right! Makes the code even simpler.

Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/RefM.scala]: Fixed and now `run` returns `IO[Nothing, Unit]`.

**Comment by jdegoes** [comment]
@ghostdogpr Nice catch! 🕺
