### PR TITLE
Optimize STM and misc code cleanup

### LINKED ISSUE #657: Testing ZIOs without DefaultRuntime uses "internal" Platform
I'm writing some tests for my ZIOs and running then with a custom `Runtime` which requires me to create a `Platform` which leads me to traits in a package named `internal` which seems scary.

### LINKED ISSUE #845: Blocking exhausts Native threads
We have ran into an issue while load testing an implementation of our system that uses ZIO `1.0-RC4` where at the end of a long run we start failing because of `OutOfMemoryError`s, which seem to report happening when trying to create a thread in the `blocking` thread pool.

Analysis seems to point to the blocking pool not reusing threads and us getting into a situation where the observed behavior of the `Blocking` pool seems to be equivalent to calling `NewThread` while under load.

I suggest 2 courses of action:
1. Provide a built-in way for users to create a `Blocking` instance that is just like the `Blocking.Live` instance, but with the ability to adjust the `keepAliveTime`, `maximumPoolSize`, and `corePoolSize` these are all options a user might want to drive from configuration for example.
2. Look into the default configuration of `Blocking`. Consider whether it actually does make sense to set the `maxPoolSize` to `Int.MaxValue`

### PR DESCRIPTION
**Pull request by jdegoes**
Found a faster way to fix the issue previously identified, and implemented this to improve performance of STM to (beyond) pre-fix levels.

Also fixed `Blocking.Live` construction to be referentially transparent, to avoid confusing creation of needless thread pools.

Finally, added a bunch of helper methods on `Runtime` to save users from having to interact with `internal.Platform`.

Fixes #845 
Fixes #657

### CODE REVIEW

File: core/shared/src/main/scala/scalaz/zio/stm/STM.scala [hunk 1]
```diff
@@ -575,6 +571,8 @@ object STM {
       protected[this] val expected: Versioned[A]
       protected[this] var newValue: A
 
+      val isNew: Boolean
```
Comment (wi101) [inline core/shared/src/main/scala/scalaz/zio/stm/STM.scala]: Nice !

Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/stm/STM.scala]: 😄 

If TRef is created inside the transaction, then it will not exist until transaction committed, so we don't need to add suspended transaction to `todo` list of new TRef. Now the `diffJournal` method just ignores all the "new" TRefs created in that transaction so process will terminate even without stable identifiers.

Also I deleted all TRef identities, since we can just use the `TRef` itself as the identity in the hash map. It cleaned up code and improved performance. 💃

File: core/shared/src/main/scala/scalaz/zio/stm/STM.scala [hunk 2]
```diff
@@ -106,10 +106,10 @@ final class STM[+E, +A] private[stm] (
    */
   final def collect[B](pf: PartialFunction[A, B]): STM[E, B] =
     new STM(
-      (journal, makeTRefId) =>
-        (self.exec(journal, makeTRefId)) match {
+      journal =>
+        self.exec(journal) match {
           case t @ TRez.Fail(_) => t
-          case TRez.Succeed(a)  => if (pf isDefinedAt a) TRez.Succeed(pf(a)) else TRez.Retry
+          case TRez.Succeed(a)  => if (pf.isDefinedAt(a)) TRez.Succeed(pf(a)) else TRez.Retry
```
Comment (wi101) [inline core/shared/src/main/scala/scalaz/zio/stm/STM.scala]: (not related) but we can simplify it:
```scala
case TRez.Succeed(a)  if pf.isDefinedAt(a) => TRez.Succeed(pf(a))
case _ => TRez.Retry
```

**Comment by jdegoes** [comment]
@wi101 Thanks for the review!
