### PR TITLE
Keep track of distinction between interruption and defect termination

### LINKED ISSUE #341: Keep track of distinction between interruption and defect termination
Currently we have only `ExitResult.Terminated`, which obscures the distinction between different types of termination:

 * Terminated due to interruption.
 * Terminated due to fatal error.

To solve this problem, we should do the following:

1. Add more cases to `ExitResult` that precisely capture the possible scenarios.
    ```scala
    trait ExitResult[+E, +A]
    object ExitResult {
      final case class Completed[A](value: A) extends ExitResult[Nothing, A]
      final case class Failed[E](error: E, defects: List[Throwable]) extends ExitResult[E, Nothing]
      final case class Interrupted(causes: List[Throwable], defects: List[Throwable]) extends ExitResult[Nothing, Nothing]
      final case class Fatal(defect: Throwable, defects: List[Throwable]) extends ExitResult[Nothing, Nothing] // Basically NonEmptyList[Throwable]
    }
    ```
2. Rename `terminate`: `IO.terminate` => `IO.fatal(t: Throwable)`, including all helpers.

This supersedes #169 and may block #267.

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #341

### CODE REVIEW

File: core/shared/src/main/scala/scalaz/zio/RefM.scala [hunk 1]
```diff
@@ -66,15 +66,15 @@ object RefM extends Serializable {
...
+    final def run(a: A, ref: Ref[A]): IO[List[Throwable], Unit] =
       interrupted.get.flatMap {
         case Some(ts) => IO.fail(ts)
         case None =>
           update(a).sandboxed.redeem({
             case Left(ts) => IO.fail(ts)
             case Right(n) => n
           }, {
-            case (b, a) => promise.complete(b).const(a)
+            case (b, a) => ref.set(a) <* promise.complete(b)
```
Comment (ghostdogpr) [inline core/shared/src/main/scala/scalaz/zio/RefM.scala]: I moved `ref.set` because there was a race condition making the tests fail occasionally.
`ref.set` must be done before completing the promise, otherwise `refM.modify` returns before the value is actually set.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 2]
```diff
@@ -26,25 +26,34 @@ sealed abstract class ExitResult[+E, +A] extends Product with Serializable { sel
...
   }
 
-  private final def combine(ts: List[Throwable], r: ExitResult[_, _]) = r match {
-    case ExitResult.Failed(_, ts2)  => ts ++ ts2
-    case ExitResult.Terminated(ts2) => ts ++ ts2
-    case _                          => ts
+  private final def combine(ts: List[Throwable], r: ExitResult[_, _]): List[Throwable] = r match {
+    case ExitResult.Failed(_, ts2)      => ts ++ ts2
+    case ExitResult.Interrupted(e, ts2) => ts ++ e ++ ts2
+    case ExitResult.Terminated(t, ts2)  => (t :: ts) ++ ts2
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: Shouldn't this be `ts ++ [t] ++ ts2`?

File: core/shared/src/main/scala/scalaz/zio/RefM.scala (hunk 1 above)
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/RefM.scala]: Submitted a dedicated PR #343

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala (hunk 2 above)
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: You're right, `ts` should be first.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 3]
```diff
@@ -858,19 +865,19 @@ object IO extends Serializable {
   final def suspend[E, A](io: => IO[E, A]): IO[E, A] = new Suspend(() => io)
 
   /**
-   * Terminates the fiber executing this action, running all finalizers.
+   * Interrupts the fiber executing this action, running all finalizers.
    */
-  final def terminate: IO[Nothing, Nothing] = terminate0(Nil)
+  final def interrupt: IO[Nothing, Nothing] = new Terminate(None, Nil)
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: This should actually be called `terminate`, because a fiber cannot (currently) interrupt itself, but it can terminate itself. There's an implicit law that:

```scala
io.terminate(t) === io.map(throw t)
```

Also now that we are requiring a `Throwable` for terminate (as would be expected by the above law), we should delete the no-parameter version of `terminate`. 

Interruption on a `Fiber` can still have a no-parameter variant, because interruption does not have to have a specified cause.

File: core/shared/src/main/scala/scalaz/zio/Errors.scala [hunk 4]
```diff
@@ -6,5 +6,6 @@ object Errors {
   final case class UnhandledError(error: Any, defects: List[Throwable] = Nil)
       extends Exception("An error was not handled by a fiber: " + error.toString())
 
-  final object TerminatedFiber extends Exception("The fiber was terminated either by a defect or an interruption")
+  final case class TerminatedFiber(causes: List[Throwable])
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/Errors.scala]: I think we should try to be as precise as we can here:

```scala
final case class TerminatedFiber(defect: Throwable, defects: List[Throwable]) extends ...
final case class InterruptedFiber(causes: List[Throwable], defects: List[Throwable]) extends ...
```

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 5]
```diff
@@ -779,7 +784,8 @@ object IO extends Serializable {
     override def tag = Tags.Supervise
   }
 
-  final class Terminate private[IO] (val causes: List[Throwable]) extends IO[Nothing, Nothing] {
+  final class Terminate private[IO] (val defect: Option[Throwable], val causes: List[Throwable])
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: We should turn `defect` into `Throwable`, rather than `Option[Throwable]`. See below comment.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 6]
```diff
@@ -224,9 +224,10 @@ private object RTS {
 
     private final def collectDefect[E, A](e: ExitResult[E, A]): Option[List[Throwable]] =
       e match {
-        case ExitResult.Terminated(ts @ _ :: _) => Some(ts)
-        case ExitResult.Failed(_, ts @ _ :: _)  => Some(ts)
-        case _                                  => None
+        case ExitResult.Interrupted(_, ts @ _ :: _) => Some(ts)
+        case ExitResult.Terminated(t, ts)           => Some(t :: ts)
+        case ExitResult.Failed(_, ts @ _ :: _)      => Some(ts)
+        case _                                      => None
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: I wonder if we should add `defects` as a method on `ExitResult` to cleanup this code and make it more useful outside `RTS`?

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 7]
```diff
@@ -459,8 +460,10 @@ private object RTS {
                                 if (curIo eq null) {
                                   result = value
                                 }
-                              case ExitResult.Terminated(ts) =>
-                                curIo = IO.terminate0(ts)
+                              case ExitResult.Interrupted(e, ts) =>
+                                curIo = IO.terminate0(Errors.TerminatedFiber(e), ts)
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: The translation of this `Interrupted` into `IO.terminate` concerns me because we are losing information and I think there will be strange edge cases.

I think you should instead say something like `curIo = interrupt(e, ts)`. It can't exactly be `interrupt` because ordinary `interrupt` method on `FiberContext` will block until interrupted (it's not intended to be called by a fiber on itself).

But it should be possible to write a `selfInterrupt` method that will call `kill0` directly, and modify `kill0` so that adding a callback is optional.

As a short-term fix, you could also do:

```scala
curIo = interrupt(...).fork
```

However, you still have the problem that `interrupt` is not designed to take defects, so you have to add those defects to those being collected in the fiber state. /cc @regiskuckaertz 

Also I suggest to use a plural naming convention on `e` to be consistent: e.g. `es`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 8]
```diff
@@ -552,12 +555,14 @@ private object RTS {
...
                       // No finalizers, simply produce error:
-                      val causes    = status.get.terminationCauses.getOrElse(Nil)
-                      val defects   = status.get.defects
-                      val allCauses = io.causes ++ causes ++ defects
+                      val causes  = status.get.terminationCauses.getOrElse(Nil)
+                      val defects = status.get.defects
 
                       curIo = null
-                      result = ExitResult.Terminated(allCauses)
+                      result = io.defect match {
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This logic will simplify when `Terminate` requires a `defect`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 9]
```diff
@@ -588,7 +593,7 @@ private object RTS {
               // At this point, all causes of interruption have been accumulated
               // in the fiber status and will be read during evaluation of this
               // action:
-              curIo = IO.terminate
+              curIo = IO.interrupt
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Hmmm, this suggests to me the solution is more complex than just introducing `selfInterrupt`.

The runtime system really wants a term in `IO` for interruption, e.g.:

```scala
class Interrupt(causes: List[Throwable], defects: List[Throwable] extends IO[Nothing, Nothing]
```

permitting a method:

```scala
object IO {
  ...
  def interrupt(causes: List[Throwable], defects: List[Throwable])
  ...
}
```

which will perform self-interruption.

Introducing this term could actually simplify some core logic because it's possible (though not certain) we could remove causes / defects from the fiber state with enough work.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 10]
```diff
@@ -26,25 +26,34 @@ sealed abstract class ExitResult[+E, +A] extends Product with Serializable { sel
...
-    case (ExitResult.Failed(e, ts), rb)                       => ExitResult.Failed(e, combine(ts, rb))
-    case (ExitResult.Terminated(ts), rb)                      => ExitResult.Terminated(combine(ts, rb))
-    case (ExitResult.Completed(_), ExitResult.Failed(e, ts))  => ExitResult.Failed(e, ts)
-    case (ExitResult.Completed(_), ExitResult.Terminated(ts)) => ExitResult.Terminated(ts)
+    case (ExitResult.Completed(a), ExitResult.Completed(b))       => ExitResult.Completed(f(a, b))
+    case (ExitResult.Failed(e, ts), rb)                           => ExitResult.Failed(e, combine(ts, rb))
+    case (ExitResult.Interrupted(e, ts), rb)                      => ExitResult.Interrupted(e, combine(ts, rb))
+    case (ExitResult.Terminated(t, ts), rb)                       => ExitResult.Terminated(t, combine(ts, rb))
+    case (ExitResult.Completed(_), ExitResult.Failed(e, ts))      => ExitResult.Failed(e, ts)
+    case (ExitResult.Completed(_), ExitResult.Interrupted(e, ts)) => ExitResult.Interrupted(e, ts)
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: This is an interesting case. What should be the result of combining `Interrupted` and `Terminated`? Which one "wins"? Left? Right? `Interrupted`? `Terminated`?

The fact any answer is arbitrary (as far as I can see) and that we have to ask this question at all suggests maybe interruption and termination are aspects of a single term.

What if we had something like:

```scala
object ExitResult[+E, +A] {
  ...
  case class Terminated(causes: List[TerminationCause]) extends ExitResult[Nothing, Nothing]
  ...
}
```

Then:

```scala
sealed trait TerminationCause
object TerminationCause {
  final case class Primary(value: Throwable) extends TerminationCause
  final case class Finalizer(value: Throwable) extends TerminationCause
  final case class Interruption(value: Throwable) extends TerminationCause
}
```

Now there's just one obvious way to combine two "terminated" states: `++`.

I think this design could simplify other code.

One problem I see is that there's no type-level guarantee of a primary exception. I'm not sure what implications that has. The other problem is that what does an empty `List` mean? I guess it means interruption without cause, if you rule out the other possibilities (?).

/cc @regiskuckaertz

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 3 above)
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Yeah I initially removed it and then put it back because it was called in RTS in case of self interruption (without throwable). That is also why I added Option[_]. I wasn't really sure what to do with it.
If we have another way to handle it (as suggested in your other comments), this can go.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala (hunk 10 above)
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: The initial goal from #267 was to distinguish if the fiber we ran was interrupted or terminated. How will we do that in that case? Search for `Interruption` in the list of causes ? What if there are some but they refer to inner fibers and not the one we're interested in?

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: That looks like a great idea. We can encode the list into the ADT to fix both problems?
```scala
case class Primary(value: Throwable) extends TerminationCause
case class Finalizer(value: Throwable) extends TerminationCause
case class Secondary(value: Throwable, primary: TerminationCause) extends TerminationCause
```

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]:
```
sealed trait TerminationCause { self =>
  def toList: List[Throwable] = self match {
    case Secondary(v, p) => p.toList.map(v :: _).reverse
    case Primary(v) => v :: Nil
    case Finalizer(v) => v :: Nil
  }
}
```

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: > The initial goal from #267 was to distinguish if the fiber we ran was interrupted or terminated.

@ghostdogpr this can still be achieved by replacing `Primary` with `Interruption` and `FatalError` cases, and perhaps carry on `isFatal` and `isInterruption` flags.

**Comment by regiskuckaertz** [comment]
A casual inspection of the case analysis on `ExitResult` shows that it mostly is binary, where the successful case is treated one way and the failed+terminated cases are treated another. If `TerminationCause` is properly designed, we can simplify `ExitResult` too:
```scala
sealed abstract class ExitResult[E, A]
case class Completed(a: A) extends ExitResult[Nothing, A]
case class Failed(cause: Error[E]) extends ExitResult[E, Nothing]

sealed abstract class Error[E]
case class Failure[E](error: E) extends Error[E]
case class Defect[E](ex: Throwable) extends Error[E]
case class Interruption[E](ex: Throwable) extends Error[E]
case class Defect[E](ex: Throwable) extends Error[E]
case class Secondary[E](ex: Throwable, primary: Error[E]) extends Error[E]
```
Using the proper terminology (#330). Thoughts?

File: core/shared/src/main/scala/scalaz/zio/Errors.scala (hunk 4 above)
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/Errors.scala]: `unsafeRun` used to throw `defect` directly. Do you mean we should throw a `TerminatedFiber` encapsulating `defect` instead?

**Comment by jdegoes** [comment]
@regiskuckaertz 

I love this! I have long felt `ExitResult` was too complicated.

I suggest, though, that we'd called the `Failed` constructor for `ExitResult` `Errored`. This is because of consistency changes so terminology #330. 

Although `Errored` is possibly not a word, so maybe change from past-tense verb into noun?

Maybe something like this:

```scala
sealed abstract class ExitResult[E, A] extends Serializable with Product {
  final def toEither: Either[Throwable, A] = ??? // Does the wrapping with Errors
}
object ExitResult {
  final case class Value(value: A) extends ExitResult[Nothing, A]
  final case class Error(value: Errors[E]) extends ExitResult[E, Nothing]

  sealed abstract class Errors[+E] extends Serializable with Product { self =>
    final def map[E1](f: E => E1): Errors[E1] = ???
    final def ++ [E1 >: E] (that: Errors[E1]): Errors[E1] = ???
    final def zip[E1](that: Errors[E1]): Errors[E, E1] = ???
    final def zipWith[E1, E2](that: Errors[E1])(f: (E, E1) => E2): Errors[E2] = self.zip(that).map(f)
  }
  object Errors {
    type NonEmptyList[A] = (A, List[A])

    final case class Failure[E](failures: NonEmptyList[E]) extends Errors[E]
    final case class Defect(defects: NonEmptyList[Throwable]) extends Errors[Nothing]
    final case class Interruption(interruptions: List[Throwable]) extends Errors[Nothing]
    final case class Secondary[E](defects: NonEmptyList[Throwable], primary: NonEmptyList[E]) extends Errors[E]
  }
}
```

The real test is, can `++` and `zip` be implemented in a reasonable (not ad hoc) fashion, which doesn't lose any information???

I changed some of the types to lists / non-empty lists to make the attempt more likely to succeed.

**Comment by ghostdogpr** [comment]
I committed a first WIP addressing some of the comments, but not the change of ExitResult yet.

Couple questions/remarks:
- now `unsafeRun` throws a `TerminatedFiber` wrapping `defect` instead of throwing `defect` directly. Is that what we want?
- for handling the new `Interrupt` class in RTS, I just duplicated the logic of `Terminate` but returning the appropriate ExitResult so that nothing is lost. I'm not familiar with that part of the code so if you have any pointer on how to improve this, please let me know.

**Comment by regiskuckaertz** [comment]
I'm going to be bold and suggest we could even rename `ExitResult` as just `Result` 🔥 There is `ExitStatus` in `App`, where I think the `Exit-` prefix makes more sense.

> The real test is, can ++ and zip be implemented in a reasonable (not ad hoc) fashion

Indeed. We may be able to get away with throwing something like `\&/` into the mix, especially when combining two `Failure`, but it would only solve half of the problem. It almost feels like the same thing than when combining free algebras using the `Inject` typeclass.

**Comment by jdegoes** [comment]
@regiskuckaertz 

In hindsight, maybe the simplified version that throws away information is better:

```scala
sealed abstract class ExitResult[E, A] extends Serializable with Product {
  final def toEither: Either[Throwable, A] = ??? // Does the wrapping with Errors

  final def map[A1](f: A => A1): ExitResult[E, A1] = ???

  final def leftMap[E1](f: E => E1): ExitResult[E1, A] = ???

  final def zip[E1 >: E, B](that: ExitResult[E1, B]): ExitResult[E1, (A, B)] = ???

  final def zipWith[E1 >: E, B, C](that: ExitResult[E1, B])(f: (A, B) => C): ExitResult[E1, C] = ???
}
object ExitResult {
  final case class Completed(value: A) extends ExitResult[Nothing, A]
  final case class Terminated(cause: Cause[E], causes: List[Cause[E]]) extends ExitResult[E, Nothing]

  sealed abstract class Cause[+E] extends Serializable with Product { self =>
    final def map[E1](f: E => E1): Cause[E1] = ???
  }
  object Cause {
    final case class Failure[E](cause: E) extends Cause[E]
    final case class Interruption(cause: Option[Throwable]) extends Cause[Nothing]
    final case class Exception(cause: Throwable) extends Cause[Nothing]
    final case class Secondary(cause: Throwable) extends Cause[Nothing]
  }
}
```

This one has solid (not ad hoc) composition properties and is pretty easy to use.

What do you think?

**Comment by regiskuckaertz** [comment]
There are a few cases where the distinction is made between the current `Failed` and `Terminated`; can we enforce that `cause` will always be a `Failure[E]` in the event of a failure? We might hide that implementation detail behind an extractor:
```scala
object Failure {
  def unapply(r: ExitResult[E, A]): Option[Failure[E]] = ???
}
```

**Comment by jdegoes** [comment]
@regiskuckaertz which code are you thinking of? It’s possible it will simplify in other ways not possible with the current design.

The problem with retaining Failed is that in some cases you have two E values you need to combine, but without the ability to combine them. Of course we could modify signature of Fiber.zipWith et al to add that capability as required.

**Comment by jdegoes** [comment]
@regiskuckaertz Also instead of List, one could use:

data Combo a
 = Leaf a
 | Then (Combo a) (Combo a)
 | Both (Combo a) (Combo a)

This lets you express sequentiality (finalizer failures, for example) or parallelism (zipping fibers). 

It’s very nearly a free semiring.

**Comment by regiskuckaertz** [comment]
> which code are you thinking of? 

Well in fact there are only "fringe" cases like `IO.onTermination`, `IO.done`, `ExitResult.mapError`.

It seems with either encoding `Secondary` is not necessary anymore, implicitly `causes` are secondary, no?

**Comment by jdegoes** [comment]
@regiskuckaertz @ghostdogpr 

Behold!

```scala
  sealed abstract class ExitResult[+E, +A] extends Product with Serializable { self =>
    import ExitResult._

    final def leftMap[E1](f: E => E1): ExitResult[E1, A] =
      self match {
        case e @ Completed(_) => e
        case Terminated(c) => Terminated(c.map(f))
      }

    final def map[A1](f: A => A1): ExitResult[E, A1] =
      self match {
        case Completed(v) => Completed(f(v))
        case e @ Terminated(_) => e
      }

    final def bimap[E1, A1](f: E => E1, g: A => A1): ExitResult[E1, A1] =
      leftMap(f).map(g)

    final def zip[E1 >: E, B](that: ExitResult[E1, B]): ExitResult[E1, (A, B)] =
      (self, that) match {
        case (Completed(a), Completed(b)) => Completed(a -> b)
        case (Terminated(l), Terminated(r)) => Terminated(l ++ r)
        case (e @ Terminated(_), _) => e
        case (_, e @ Terminated(_)) => e
      }

    final def zipPar[E1 >: E, B](that: ExitResult[E1, B]): ExitResult[E1, (A, B)] =
      (self, that) match {
        case (Completed(a), Completed(b)) => Completed(a -> b)
        case (Terminated(l), Terminated(r)) => Terminated(l && r)
        case (e @ Terminated(_), _) => e
        case (_, e @ Terminated(_)) => e
      }

    final def zipWith[E1 >: E, B, C](that: ExitResult[E1, B])(f: (A, B) => C): ExitResult[E1, C] =
      self.zip(that).map(f.tupled)
  }
  object ExitResult {
    final def point[A](a: A): ExitResult[Nothing, A] = Completed(a)

    final case class Completed[A](value: A) extends ExitResult[Nothing, A]
    final case class Terminated[E](cause: Cause[E]) extends ExitResult[E, Nothing]

    sealed abstract class Cause[+E] extends Product with Serializable { self =>
      import Cause._

      final def ++ [E1 >: E](that: Cause[E1]): Cause[E1] =
        Then(self, that)

      final def && [E1 >: E](that: Cause[E1]): Cause[E1] =
        Both(self, that)

      final def map[E1](f: E => E1): Cause[E1] = self match {
        case Failure(value) => Failure(f(value))
        case c @ Exception(_) => c
        case c @ Interruption(_) => c
        case c @ Secondary(_) => c

        case Then(left, right) => Then(left.map(f), right.map(f))
        case Both(left, right) => Both(left.map(f), right.map(f))
      }

      final def failures[E1 >: E]: Set[E1] =
        self.fold(Set.empty[E1]) {
          case (z, Failure(v)) => z + v
        }

      final def exceptions: List[Throwable] =
        (self.fold(List.empty[Throwable]) {
          case (z, Exception(v)) => v :: z
        }).reverse

      final def interruptions: Option[List[Throwable]] =
        (self.fold(Option.empty[List[Throwable]]) {
          case (z, Interruption(v)) =>
            z.fold(Some(v :: Nil))(vs => Some(v :: vs))
        }).map(_.reverse)

      final def secondaries: List[Throwable] =
        (self.fold(List.empty[Throwable]) {
          case (z, Secondary(v)) => v :: z
        }).reverse

      final def fold[Z](z: Z)(f: PartialFunction[(Z, Cause[E]), Z]): Z =
        (f.lift(z -> self).getOrElse(z), self) match {
          case (z, Then(left, right)) => right.fold(left.fold(z)(f))(f)
          case (z, Both(left, right)) => right.fold(left.fold(z)(f))(f)

          case (z, c) => z
        }
    }
    object Cause {
      final def point[E](e: => E): Cause[E] = Failure(e)

      final case class Failure[E](value: E) extends Cause[E]
      final case class Exception(value: Throwable) extends Cause[Nothing]
      final case class Interruption(value: Throwable) extends Cause[Nothing]
      final case class Secondary(value: Throwable) extends Cause[Nothing]

      final case class Then[E](left: Cause[E], right: Cause[E]) extends Cause[E] { self =>
        final def flatten: Set[Cause[E]] = {
          def flattenThen(c: Cause[E]): Set[Cause[E]] = c match {
            case Then(left, right) => flattenThen(left) ++ flattenThen(right)
            case x => Set(x)
          }

          flattenThen(left) ++ flattenThen(right)
        }

        override final def hashCode: Int = flatten.hashCode

        override final def equals(that: Any): Boolean = that match {
          case that : Both[_] => self.flatten.equals(that.flatten)
          case _ => false
        }
      }
      final case class Both[E](left: Cause[E], right: Cause[E]) extends Cause[E] { self =>
        final def flatten: Set[Cause[E]] = {
          def flattenBoth(c: Cause[E]): Set[Cause[E]] = c match {
            case Both(left, right) => flattenBoth(left) ++ flattenBoth(right)
            case x => Set(x)
          }

          flattenBoth(left) ++ flattenBoth(right)
        }

        override final def hashCode: Int = flatten.hashCode

        override final def equals(that: Any): Boolean = that match {
          case that : Both[_] => self.flatten.equals(that.flatten)
          case _ => false
        }
      }
    }
  }
```

Not sure these are the best names and there could be more helpers (e.g. `ExitResult.completed`, etc.).

It may be possible to improve the type safety of `zip` by storing a proof that one side or the other does not contain an `E`.

**Comment by jdegoes** [comment]
@regiskuckaertz What do we lose with the above representation, if anything?

**Comment by ghostdogpr** [comment]
@jdegoes @regiskuckaertz 
I just pushed the new implementation with the ExitResult design that you suggested. Probably got a bunch of things wrong 😅I count on your help!

**Comment by regiskuckaertz** [comment]
@jdegoes me likey! off the top of my head, I cannot think of anything missing. Excited to see @ghostdogpr 's progress on this!

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 11]
```diff
@@ -9,56 +10,192 @@ package scalaz.zio
...
+        case (z, _) => z
+      }
+
+    final def toThrowable(causes: List[Throwable] = Nil): Throwable =
+      self match {
+        case Failure(error)      => Errors.UnhandledError(error, causes)
+        case Exception(defect)   => Errors.TerminatedFiber(defect, causes)
+        case Interruption(cause) => Errors.InterruptedFiber(cause.map(_ :: Nil).getOrElse(Nil), causes)
+        case Then(left, right)   => left.toThrowable(right.toThrowable() :: causes)
+        case Both(left, right)   => Errors.ParallelFiberError(left.toThrowable(), right.toThrowable(), causes)
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: It looks right to me.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 12]
```diff
@@ -9,56 +10,192 @@ package scalaz.zio
...
+      }
+
+    final def failure: Option[E] = self match {
+      case Failure(e)      => Some(e)
+      case Exception(_)    => None
+      case Interruption(_) => None
+      case Then(left, _)   => left.failure
+      case Both(_, _)      => None
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: A wildcard pattern for all but the two special cases would do here. Also worth adding a `@tailrec` annotation.

File: core/shared/src/main/scala/scalaz/zio/Fiber.scala [hunk 13]
```diff
@@ -40,9 +40,12 @@ trait Fiber[+E, +A] { self =>
    * result in a catchable error, _if_ that error does not result from interruption.
    */
   final def join: IO[E, A] = observe.flatMap {
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/Fiber.scala]: This whole expression can be shortened to `observe.flatMap(IO.done)`

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 14]
```diff
@@ -141,9 +141,12 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
   final def parWith[E1 >: E, B, C](that: IO[E1, B])(f: (A, B) => C): IO[E1, C] = {
     def coordinate[A, B](f: (A, B) => C)(winner: Fiber[E1, A], loser: Fiber[E1, B]): IO[E1, C] =
       winner.observe.flatMap {
-        case ExitResult.Completed(_)   => winner.zipWith(loser)(f).join
-        case ExitResult.Failed(e, ts)  => loser.interrupt *> IO.fail0(e, ts)
-        case ExitResult.Terminated(ts) => loser.interrupt *> IO.terminate0(ts)
+        case ExitResult.Completed(_) => winner.zipWith(loser)(f).join
+        case ExitResult.Terminated(cause) =>
+          loser.interrupt *> (cause.failure match {
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: This whole pattern is bound to occur in several places, what about adding
```
trait Cause[E] {
  def toIO: IO[E, Nothing]
}
```
?

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 15]
```diff
@@ -18,11 +19,9 @@ trait RTS {
    * Effectfully and synchronously interprets an `IO[E, A]`, either throwing an
    * error, running forever, or producing an `A`.
    */
-  final def unsafeRun[E, A](io: IO[E, A]): A = unsafeRunSync(io) match {
-    case ExitResult.Completed(v)       => v
-    case ExitResult.Terminated(Nil)    => throw Errors.TerminatedFiber
-    case ExitResult.Terminated(t :: _) => throw t
-    case ExitResult.Failed(e, ts)      => throw Errors.UnhandledError(e, ts)
+  final def unsafeRun[E, A](io: IO[E, A]): A = unsafeRunSync(io).toEither match {
```
Comment (regiskuckaertz) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Nice 😍

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 16]
```diff
@@ -252,7 +244,8 @@ private object RTS {
           case a: IO.Redeem[_, _, _, _] =>
             errorHandler = a.err.asInstanceOf[Any => IO[Any, Any]]
           case f0: Finalizer =>
-            val f: IO[Nothing, Option[List[Throwable]]] = fork(f0.finalizer, _ => IO.unit).observe.map(collectDefect)
+            val f: IO[Nothing, Option[List[Throwable]]] =
+              fork(f0.finalizer, _ => IO.unit).observe.map((a: ExitResult[Nothing, Unit]) => a.exceptions)
```
Comment (regiskuckaertz) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: would `.map(_.exceptions)` work too?

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 17]
```diff
@@ -428,7 +422,7 @@ private object RTS {
                         val defects = status.get.defects
 
                         curIo = null
-                        result = ExitResult.Failed(error, defects)
+                        result = ExitResult.Terminated(Cause.failure(error, defects))
```
Comment (regiskuckaertz) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: We may want to add utility functions for that, like `ExitResult.failed(error, defects)`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 16 above)
Comment (ghostdogpr) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: For some reason compiling throws a `missing parameter type for expanded function` without it.

**Comment by ghostdogpr** [comment]
@regiskuckaertz thanks for the review! I addressed everything except the zip/zipWith comment which I didn't quite get (yet).

**Comment by regiskuckaertz** [comment]
@ghostdogpr fantastic 🎉 My bad, I wasn't clear. What I meant was if we write `zipWith` as such:
```scala
def zipWith[E1 >: E, B, C](
  that: ExitResult[E1, B])(
  f: (A, B) => C, 
  g: (Cause[E], Cause[E1]) => Cause[E1]
): ExitResult[E1, C] =???
```
then both `zip` and `zipPar` can become one liners. In both cases, `f` would just make a tuple of its two arguments (`(_, _)`), whereas `g` would be sequential concat in `zip` case (`++`) and parallel concat in `zipPar` case (`&&`).

**Comment by ghostdogpr** [comment]
@regiskuckaertz got it! Currently `zip` and `zipPar` are not used, only `zipWith` is (in `Fiber`). Which `g` do you think we should use? `_ && _`? (currently `Both` is not used anywhere)

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 18]
```diff
@@ -877,24 +877,17 @@ private object RTS {
     }
 
     final def reportErrors(v: ExitResult[E, A]): Unit =
-      v match {
-        case ExitResult.Failed(error, defects) =>
+      v.toEither match {
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This is a good simplification.

File: core/jvm/src/test/scala/scalaz/zio/RTSSpec.scala [hunk 19]
```diff
@@ -304,7 +311,7 @@ class RTSSpec(implicit ee: ExecutionEnv) extends AbstractRTSSpec with AroundTime
     // FIXME: Is this an issue with thread synchronization?
     while (reported eq null) Thread.`yield`()
 
-    reported must_=== List(ExampleError)
+    reported.head.asInstanceOf[TerminatedFiber].defect must_=== ExampleError
```
Comment (jdegoes) [inline core/jvm/src/test/scala/scalaz/zio/RTSSpec.scala]: Rather than using a cast, you can just use `must_==`.

File: core/shared/src/main/scala/scalaz/zio/Async.scala [hunk 20]
```diff
@@ -14,11 +15,10 @@ package scalaz.zio
 sealed abstract class Async[+E, +A] extends Product with Serializable { self =>
   def fold[E1, B](
     f: A => ExitResult[E1, B],
-    g: (E, List[Throwable]) => ExitResult[E1, B],
-    h: List[Throwable] => ExitResult[E1, B]
+    g: Cause[E] => ExitResult[E1, B]
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/Async.scala]: Nice simplification!

File: core/shared/src/main/scala/scalaz/zio/Errors.scala [hunk 21]
```diff
@@ -6,5 +6,12 @@ object Errors {
...
       extends Exception("An error was not handled by a fiber: " + error.toString())
 
-  final object TerminatedFiber extends Exception("The fiber was terminated either by a defect or an interruption")
+  final case class TerminatedFiber(defect: Throwable, defects: List[Throwable])
+      extends Exception("The fiber was terminated by a defect")
+
+  final case class InterruptedFiber(causes: List[Throwable], defects: List[Throwable])
+      extends Exception("The fiber was terminated by an interruption")
+
+  final case class ParallelFiberError(left: Throwable, right: Throwable, defects: List[Throwable])
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/Errors.scala]: As stated elsewhere, I think we can delete all these types and just have one (`FiberHalt` or something).

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 22]
```diff
@@ -9,56 +10,203 @@ package scalaz.zio
...
-      case Failed(e, ts) => failed(e, ts)
-      case Terminated(e) => interrupted(e)
+      case Completed(v)      => completed(v)
+      case Terminated(cause) => terminated(cause)
+    }
+}
+object ExitResult {
+
+  final case class Completed[A](value: A)         extends ExitResult[Nothing, A]
+  final case class Terminated[E](cause: Cause[E]) extends ExitResult[E, Nothing]
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: I'm increasingly convinced we should call this `Halted`:

```scala
final case class Halted[E](cause: Cause[E]) extends ExitResult[E, Nothing]
```

Either a fiber _completes_ or it _halts_. Either it ends up _completed_ or it ends up _halted_. Halting can occur for different _causes_. Etc.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 23]
```diff
@@ -9,56 +10,203 @@ package scalaz.zio
...
+        case Failure(error)      => Errors.UnhandledError(error, causes)
+        case Exception(defect)   => Errors.TerminatedFiber(defect, causes)
+        case Interruption(cause) => Errors.InterruptedFiber(cause.map(_ :: Nil).getOrElse(Nil), causes)
+        case Then(left, right)   => left.toThrowable(right.toThrowable() :: causes)
+        case Both(left, right)   => Errors.ParallelFiberError(left.toThrowable(), right.toThrowable(), causes)
+      }
+
+    def toIO: IO[E, Nothing] = self.failure match {
+      case Some(error) => IO.fail0(error, self.exceptions)
+      case None        => IO.terminateWithCause(self)
```
[the remark this answers is not in the document]
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: It's my bad. I did not think far enough to realise that with `Cause[E]`, the distinction between `IO.fail` and `IO.terminate` disappears. That implies _a lot_ of code reduction in RTS 🎉

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 24]
```diff
@@ -9,56 +10,203 @@ package scalaz.zio
...
+          )
+      }
+
+    final def apply[E](cause: Cause[E], defects: List[Throwable]): Cause[E] =
+      defects.foldLeft[Cause[E]](cause)((causes, defect) => causes ++ Exception(defect))
+
+    final case class Failure[E](value: E)                   extends Cause[E]
+    final case class Exception(value: Throwable)            extends Cause[Nothing]
+    final case class Interruption(value: Option[Throwable]) extends Cause[Nothing]
+
```
[the remark this answers is not in the document]
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: This is kind of veering off the terminology you described [in that ticket](https://github.com/scalaz/scalaz-zio/issues/330), isn't that going to muddy the waters?

File: core/shared/src/main/scala/scalaz/zio/Fiber.scala [hunk 25]
```diff
@@ -74,11 +70,11 @@ trait Fiber[+E, +A] { self =>
   final def zipWith[E1 >: E, B, C](that: => Fiber[E1, B])(f: (A, B) => C): Fiber[E1, C] =
     new Fiber[E1, C] {
       def observe: IO[Nothing, ExitResult[E1, C]] =
-        self.observe.seqWith(that.observe)(_.zipWith(_)(f))
+        self.observe.seqWith(that.observe)(_.zipWith(_)(f, _ ++ _))
```
[the remark this answers is not in the document]
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Fiber.scala]: ha, again my mistake 😅

[the remark this answers is not in the document]
Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/Fiber.scala]: My mistake for sloppy types. 😆 I think it would be great if we modified `++` so that you can only combine `l` and `r` when either `l: Cause[Nothing]` or `r: Cause[Nothing]`. 

The reason being: a fiber cannot fail for 2 different `E`. 

It's possible to solve this with some effort:

```scala
trait OneFailure[E1, E2] {
      type Output

      def left: E1 => Output
      def right: E2 => Output

      def proof: Either[E1 => Nothing, E2 => Nothing]
    }
    trait OneFailureInstances0 extends OneFailureInstances1 {
      implicit def leftFailure[E]: Aux[E, Nothing, E] =
        new OneFailure[E, Nothing] {
          type Output = E

          def left: E => Output = identity
          def right: Nothing => Output = identity

          def proof = Right(identity)
        }
    }
    trait OneFailureInstances1 {
      type Aux[A, B, C] = OneFailure[A, B] {
        type Output = C
      }
      implicit def rightFailure[E]: Aux[Nothing, E, E] =
        new OneFailure[Nothing, E] {
          type Output = E

          def left: Nothing => Output = identity
          def right: E => Output = identity

          def proof = Left(identity)
        }
    }
    object OneFailure extends OneFailureInstances0 {
      def concat[A, B, C](l: List[A], r: List[B])(implicit ev: OneFailure.Aux[A, B, C]): List[C] =
        ???

      concat(List.empty[Nothing], List[Int](1, 2, 3)): List[Int]
      concat(List[Int](1, 2, 3), List.empty[Nothing]): List[Int]
      concat(List.empty[Nothing], List.empty[Nothing]): List[Int]
    }
```

Then you will get a type error if you try to `++` two `Cause` but one of them is not known to have `Nothing` for its `E`.

This would have prevented the above implementation, but would still allow use of `++` to concatenate finalizer errors onto a primary cause.

[the remark this answers is not in the document]
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/Fiber.scala]: Would there be any disadvantage in moving `++` right into `OneFailure`?
```
class OneFailure e1 e2 f | e1 e2 -> f where (++) :: e1 -> e2 -> f
instance OneFailure (Cause Nothing) (Cause Nothing) (Cause Nothing) ...
instance OneFailure (Cause Nothing) (Cause e) (Cause e) ...
instance OneFailure (Cause e) (Cause Nothing) (Cause e) ...
```
I know these overlap 😓

File: core/jvm/src/test/scala/scalaz/zio/RTSSpec.scala (hunk 19 above)
Comment (ghostdogpr) [reply core/jvm/src/test/scala/scalaz/zio/RTSSpec.scala]: It was the case initially but the test failed. The problem is that I can't compare `TerminatedFiber` directly because the one generated in the code and the one from the test have a different call stack and are not equal. I can only compare `ExampleError` but I need the cast to access it.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 26]
```diff
@@ -9,56 +10,203 @@ package scalaz.zio
...
+    final def interruption(causes: List[Throwable], defects: List[Throwable] = Nil): Cause[Nothing] =
+      causes match {
+        case Nil => Cause(Interruption(None), defects)
+        case head :: tail =>
+          tail.foldLeft(Cause(Interruption(Some(head)), defects))(
+            (causes, cause) => causes ++ Interruption(Some(cause))
+          )
+      }
+
+    final def apply[E](cause: Cause[E], defects: List[Throwable]): Cause[E] =
```
[the remark this answers is not in the document]
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: Changing to `def withDefects` directly on the Cause class.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 27]
```diff
@@ -1039,8 +1043,9 @@ object IO extends Serializable {
    */
   final def unsandbox[E, A](v: IO[Either[List[Throwable], E], A]): IO[E, A] =
     v.catchAll[E, A] {
-      case Right(e) => IO.fail(e)
-      case Left(ts) => IO.terminate0(ts)
+      case Right(e)      => IO.fail(e)
```
[the remark this answers is not in the document]
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: How about catchAll? Still taking an `E`?

**Comment by kaishh** [comment]
`Cause[E] => IO[E2, B]` means we have to stop unwinding the stack on termination on every single error handler, even though most of them won't catch termination.

**Comment by kaishh** [comment]
Also, we should be careful to not allow catching interruption except in very special combinators, in particular .run and .sandbox shouldn't catch interruption

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 27 above)
[the remark this answers is not in the document]
Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Isn't this going to be
```scala
def sandbox[E1 <: E]: IO[Cause[E1], A]
```
? If the action failed because of an unchecked error or interruption, we get a `Cause[Nothing]`.

**Comment by jdegoes** [comment]
> Cause[E] => IO[E2, B] means we have to stop unwinding the stack on termination on every single error handler, even though most of them won't catch termination.

I think we can fix this later by adding a "hints" field to the `Redeem` constructor that specifies what they rethrow and takes the appropriate shortcut.

> Also, we should be careful to not allow catching interruption except in very special combinators, in particular .run and .sandbox shouldn't catch interruption

Agreed. I don't even think it should be possible in user-land to catch interruption, other than perhaps in `run` (I think run already "catches" interruption).

**Comment by jdegoes** [comment]
> Thanks for the deep review. I've applied the majority of changes but didn't push it yet as it's not fully working, I will continue tomorrow. That's quite a big refactor!

Yes, indeed. Thanks for taking on such a big project. 😄 

> There's just one thing I'm struggling with at the moment about Redeem. @jdegoes you suggested to replace E by Cause[E] in the Redeem class. But your intent is to keep def redeem with E the way it is, right? attempt, catchAll, etc would all keep the same prototype as well, right?

Yes, we don't want to change those. For the most part, the more powerful redeem is an implementation detail that we'll exploit in various ways, but not one we'll expose to the user.

> If the answer is yes, how would you implement def redeem with the new Redeem? We need to provide a Cause[E] => IO[E2, B] but we have a E => IO[E2, B]. I'm able to make a Cause[E] => Cause[IO[E2, B]] but not a IO[E2, B] directly.

If there's an `E` inside the cause, then you pass it to the `onError` handler. If, on the other hand, there is no `E`, then you fail with the original cause (which will give you `IO[E2, B]`). I think you'll actually get `IO[E, B]`, but you can safely cast that to `IO[E2, B]` in precisely the case there is no `E` inside the cause. In fact, we could probably add a method to `Cause`, something like: `def checkedOrRefail[E2]: Either[Cause[E2], E]` to express that and keep the API safe.

**Comment by ghostdogpr** [comment]
@jdegoes @regiskuckaertz ready for your review again!

As per your suggestions, I merged `Fail` and `Terminate` into a single class. Also merged the errors into `FiberFailure`, changed `Redeem` to take a `Cause` and used the new names `Checked`, `Unchecked`, etc. The tests all pass 😬

**Comment by regiskuckaertz** [comment]
@ghostdogpr Smashing ⚡️ This is making ZIO so much better! I'll properly review asap.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 28]
```diff
@@ -231,31 +227,24 @@ private object RTS {
...
-     * Catches an exception, returning a (possibly null) finalizer action that
-     * must be executed. It is painstakingly *guaranteed* that the stack will be
-     * empty in the sole case the exception was not caught by any exception
-     * handler—i.e. the exceptional case.
+     * Empties the stack, collecting all finalizers and coalescing them into an
+     * action that produces a list (possibly empty) of errors during finalization.
+     * If needed, catch exceptions and apply redeem error handling.
      */
-    final def catchError: IO[Nothing, Option[List[Throwable]]] = {
+    final def interruptStack(catchError: Boolean): IO[Nothing, Option[List[Throwable]]] = {
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: I would call this `unwindStack`, and I think the return type is a holdover from the old model. I'd change to:

```scala
IO[Nothing, Cause[Nothing]]
```

Indeed, anytime you see `List[Throwable]`, it's likely a holdover, and probably needs to be changed to `Cause[Nothing]`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 29]
```diff
@@ -231,31 +227,24 @@ private object RTS {
...
       var errorHandler: Any => IO[Any, Any]               = null
       var finalizer: IO[Nothing, Option[List[Throwable]]] = null
 
       // Unwind the stack, looking for exception handlers and coalescing
       // finalizers.
       while ((errorHandler eq null) && !stack.isEmpty) {
         stack.pop() match {
-          case a: IO.Redeem[_, _, _, _] =>
+          case a: IO.Redeem[_, _, _, _] if catchError =>
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: I like how, at long last, `catchError` can be unified with `interruptStack`! 😍 

They had basically the same logic.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 30]
```diff
@@ -473,10 +399,8 @@ private object RTS {
                                 if (curIo eq null) {
                                   result = value
                                 }
-                              case ExitResult.Terminated(ts) =>
-                                curIo = IO.terminate0(ts)
-                              case ExitResult.Failed(e, ts) =>
-                                curIo = IO.fail0(e, ts)
+                              case ExitResult.Failed(cause) =>
+                                curIo = cause.toIO
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: At this point, `toIO` is probably too simple to exist, and this can be replaced by `IO.fail0(cause)`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 31]
```diff
@@ -555,24 +479,43 @@ private object RTS {
                       io.value.ensuring(exitSupervision(io.supervisor))
 
                   case IO.Tags.Terminate =>
-                    val io = curIo.asInstanceOf[IO.Terminate]
+                    val io = curIo.asInstanceOf[IO.Terminate[E]]
 
-                    val finalizer = interruptStack
+                    val finalizer = interruptStack(io.cause.checkedFirst.isDefined)
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Probably worth adding:

```scala
def isChecked: Boolean
```

to `Cause`, so we can eliminate the large allocation overhead that `cause.checkedFirst.isDefined` will have.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 32]
```diff
@@ -555,24 +479,43 @@ private object RTS {
...
-                      val causes    = status.get.terminationCauses.getOrElse(Nil)
-                      val defects   = status.get.defects
-                      val allCauses = io.causes ++ causes ++ defects
+                    if (stack.isEmpty) {
+                      // Error not caught, stack is empty:
+                      if (finalizer eq null) {
+                        // No finalizer, so immediately produce the error.
+                        curIo = null
+
+                        val cause = (io.cause, status.get.terminationCause) match {
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: First, `terminationCause` should be replaced by `interrupted: Boolean` inside the fiber state. This is because `interrupt` will _no longer_ accept a list of throwables. That is, interruption will always carry no additional information on the cause of interruption.

This means you can replace all of this `cause` code by something like:

```scala
val cause = if (status.get.interrupted) io.cause ++ Cause.interrupt else io.cause
```

I see also the old code used `status.get.defects` to accumulate errors during finalization. I think you are now accumulating them into `terminationCause`. We need to change that, ideally by no longer storing finalization errors into the ref, but just accumulating them directly.

However, in this branch, there are no finalizers, so the above simplification should be enough.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 33]
```diff
@@ -555,24 +479,43 @@ private object RTS {
...
-                      val finalization = finalizer.flatMap(accumFailures)
-                      val completer    = io
+                      // Error caught:
+                      val handled = nextInstr[E](io.cause, stack)
+
+                      if (finalizer eq null) {
+                        curIo = handled
+                      } else {
+                        // Must run finalizer first:
+                        val finalization = finalizer.flatMap(accumFailures)
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This part requires more intricate surgery. Right now:

1. `handled` is created to handle the `io.cause`. But that's wrong, because we need to insert the finalizer failures into `io.cause`, before we can create `handled`.
2. The finalizer failures are being accumulated into the fiber status but not really used, which means they'll sit around until the fiber finishes (I assume).

I think the new code for this section should be something like:

```scala
if (finalizer eq null) {
  curIo = nextInstr[E](io.cause, stack)
} else {
  curIo = doNotInterrupt(finalizer).map(cause => io.cause ++ cause)
}
```

Then after the new cause is computed (as the concat of the `io.cause` and the finalizer failure causes), then the next operation to be popped off the stack will be `nextInstr[E](io.cause ++ [finalizer cause])` so the handler will get the full cause.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 34]
```diff
@@ -606,7 +549,7 @@ private object RTS {
               // At this point, all causes of interruption have been accumulated
               // in the fiber status and will be read during evaluation of this
               // action:
-              curIo = IO.terminate
+              curIo = IO.interrupt
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: The comment can be revised since we're deleting causes of interruption and turning `terminationCauses` into a simple `interrupted: Boolean`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 35]
```diff
@@ -647,16 +590,31 @@ private object RTS {
     private final def addFailures(ts: List[Throwable]): Unit = {
       val oldStatus = status.get
       oldStatus match {
-        case x @ Executing(_, ts0, _) =>
-          if (!status.compareAndSet(oldStatus, x.copy(defects = ts0 ++ ts))) addFailures(ts) else ()
+        case x @ Executing(cause, _) =>
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: `accumFailures`, `addFailures`, and `addDefects` can all be deleted. Any place using them needs to be changed (I think I caught all of them in the above review).

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 36]
```diff
@@ -671,9 +629,8 @@ private object RTS {
           if (io eq null) done(value.asInstanceOf[ExitResult[E, A]])
           else evaluate(io)
 
-        case ExitResult.Failed(t, ts) => evaluate(IO.fail0[E](t, ts))
-
-        case ExitResult.Terminated(ts) => evaluate(IO.terminate0(ts))
+        case ExitResult.Failed(cause) =>
+          evaluate(cause.toIO)
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Replace by `evaluate(IO.fail0(cause))`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 37]
```diff
@@ -849,25 +805,28 @@ private object RTS {
...
-        case ExitResult.Failed(e, _) => e
-        case ExitResult.Terminated(ts) =>
-          rts.submit(rts.unsafeRun(unhandled(ts)))
-          cb(ExitResult.Terminated(ts))
-      }.fold(identity, ExitResult.Failed(_, _), ExitResult.Terminated(_))
+        case ExitResult.Failed(cause) =>
+          cause.checkedFirst match {
+            case Some(_) =>
+            case None =>
+              rts.submit(rts.unsafeRun(unhandled(cause.toThrowable :: Nil)))
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: I don't know why the `unhandled` exception handler is being invoked during `register`. Seems likely wrong. I'd delete that line. The place to do that is `done`.

@regiskuckaertz Can you take a look? This seems really strange to me.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 38]
```diff
@@ -932,7 +884,7 @@ private object RTS {
                 }
             }
 
-            val finalizer = interruptStack
+            val finalizer = interruptStack(false)
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: It looks like we're losing these finalizer failures. I'd put a big `FIXME` and we can solve it in a separate ticket. This one is big enough! 😆

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 28 above)
Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Testing.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 39]
```diff
@@ -1001,32 +953,27 @@ private object RTS {
 
   sealed abstract class FiberStatus[E, A] extends Serializable with Product {
 
-    /** causes passed in when explicitly interrupting the fiber */
-    def terminationCauses: Option[List[Throwable]]
+    /** cause of the fiber termination if any */
+    def terminationCause: Option[Cause[E]]
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This will change to `interrupted: Boolean`.

File: core/jvm/src/test/scala/scalaz/zio/AbstractRTSSpec.scala [hunk 40]
```diff
@@ -5,8 +5,7 @@ import org.specs2.Specification
 trait AbstractRTSSpec extends Specification with RTS {
   override def defaultHandler: List[Throwable] => IO[Nothing, Unit] =
     IO.traverse(_) {
-      case Errors.UnhandledError(_, _) => IO.unit
-      case Errors.TerminatedFiber      => IO.unit
-      case e                           => IO sync Console.err.println(s"""[info] Discarding ${e.getClass.getName} ("${e.getMessage}")""")
+      case Errors.FiberFailure(_) => IO.unit
+      case e                      => IO sync Console.err.println(s"""[info] Discarding ${e.getClass.getName} ("${e.getMessage}")""")
```
Comment (jdegoes) [inline core/jvm/src/test/scala/scalaz/zio/AbstractRTSSpec.scala]: So clean!

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 41]
```diff
@@ -171,8 +167,8 @@ private object RTS {
    */
   final class FiberContext[E, A](rts: RTS, val fiberId: FiberId, val unhandled: List[Throwable] => IO[Nothing, Unit])
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: The type of `unhandled` needs to change from `List[Throwable] => IO[Nothing, Unit]` to `Cause[Nothing] => IO[Nothing, Unit]`.

Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This should simplify code since usually `cause.toThrowable :: Nil` is being passed to `unhandled`.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 42]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+    g: (Cause[E], Cause[E1]) => Cause[E1]
+  ): ExitResult[E1, C] =
+    (self, that) match {
+      case (Completed(a), Completed(b)) => Completed(f(a, b))
+      case (Failed(l), Failed(r))       => Failed(g(l, r))
+      case (e @ Failed(_), _)           => e
+      case (_, e @ Failed(_))           => e
+    }
+
+  final def exceptions: Option[List[Throwable]] = self match {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: If we don't lose this, we should think about deleting it, because it is "lossy".

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 43]
```diff
@@ -9,56 +10,203 @@ package scalaz.zio
...
+    case Completed(_)      => None
+    case Terminated(cause) => Some(cause.exceptions)
   }
 
-  final def map[B](f: A => B): ExitResult[E, B] = self match {
-    case Completed(a) => Completed(f(a))
-    case x            => x.asInstanceOf[ExitResult[E, B]]
+  final def <>[E1, A1 >: A](that: ExitResult[E1, A1]): ExitResult[E1, A1] = self.failure match {
+    case Some(_) => that
+    case None    => self.asInstanceOf[ExitResult[E1, A1]]
```
[the remark this answers is not in the document]
Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: You should be able to use `checkedOrRefail` here.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 44]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+
+  final def <>[E1, A1 >: A](that: ExitResult[E1, A1]): ExitResult[E1, A1] = self.failure match {
+    case Some(_) => that
+    case None    => self.asInstanceOf[ExitResult[E1, A1]]
   }
 
-  final def mapError[E2, A1 >: A](f: E => ExitResult[E2, A1]): ExitResult[E2, A1] = self match {
-    case ExitResult.Failed(e, _) => f(e)
-    case x                       => x.asInstanceOf[ExitResult[E2, A1]]
+  final def failure: Option[E] = self match {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: If you don't lose this, delete it, because it loses information. At the very least, change the name to `checked`.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 45]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
     self match {
       case Completed(v)  => completed(v)
-      case Failed(e, ts) => failed(e, ts)
-      case Terminated(e) => interrupted(e)
+      case Failed(cause) => terminated(cause)
     }
+}
+object ExitResult {
+
+  final case class Completed[A](value: A)     extends ExitResult[Nothing, A]
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: I'd rename this to `Succeeded`, and add _and_ use two more helper functions:

```scala
def succeeded[A](a: A): ExitResult[Nothing, A] = ...

def failed[E](cause: Cause[E]): ExitResult[E, Nothing] = ...
```

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 46]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+  final case class Failed[E](cause: Cause[E]) extends ExitResult[E, Nothing]
+
+  final def checked[E](error: E): ExitResult[E, Nothing] = ExitResult.Failed(Cause.checked(error))
+  final def interrupted(causes: List[Throwable]): ExitResult[Nothing, Nothing] =
+    ExitResult.Failed(Cause.interrupt(causes))
+  final def unchecked(t: Throwable): ExitResult[Nothing, Nothing] = ExitResult.Failed(Cause.unchecked(t))
+
+  sealed abstract class Cause[+E] extends Product with Serializable { self =>
+    import Cause._
+    final def ++[E1 >: E](that: Cause[E1]): Cause[E1] =
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: @regiskuckaertz We should try to make this type safe later.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 47]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+        .reverse
+
+    final def unchecked: List[Throwable] =
+      self
+        .fold(List.empty[Throwable]) {
+          case (z, Unchecked(v)) => v :: z
+        }
+        .reverse
+
+    final def interruptions: Option[List[Throwable]] =
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: This should be changed to: 

```scala
final def interrupted: Boolean
```

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 48]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+      (f.lift(z -> self).getOrElse(z), self) match {
+        case (z, Then(left, right)) => right.fold(left.fold(z)(f))(f)
+        case (z, Both(left, right)) => right.fold(left.fold(z)(f))(f)
+
+        case (z, _) => z
+      }
+
+    final def toThrowable: Throwable = FiberFailure(self)
+
+    final def toIO: IO[E, Nothing] = IO.fail0(self)
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: This should be deleted. It's so simple now it's just proxying and adding one unnecessary layer of indirection.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 49]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+
+    final def checkedFirst: Option[E] = checked.headOption
+
+    final def withDefects(defects: List[Throwable]): Cause[E] =
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: This should definitely be deleted. Any code using it is probably outdated and needs modernizing in light of these changes.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 50]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+      defects.foldLeft[Cause[E]](self)((causes, defect) => causes ++ Unchecked(defect))
+
+    final def checkedOrRefail[E2]: Either[E, Cause[E2]] = self.checkedFirst match {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: The type signature of this can be simplified:

```scala
 final def checkedOrRefail: Either[E, Cause[Nothing]]
```

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 51]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
-    case ExitResult.Failed(_, ts2)  => ts ++ ts2
-    case ExitResult.Terminated(ts2) => ts ++ ts2
-    case _                          => ts
+  object Cause {
+
+    final def checked[E](error: E): Cause[E] = Checked(error)
+
+    final def unchecked(defect: Throwable): Cause[Nothing] = Unchecked(defect)
+
+    final def interrupt(causes: List[Throwable]): Cause[Nothing] =
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: Change to:

```scala
final def interrupted: Cause[Nothing]
```

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 32 above)
Comment (regiskuckaertz) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: ⚡️

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 52]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+        case Nil => Interruption(None)
+        case head :: tail =>
+          tail.foldLeft[Cause[Nothing]](Interruption(Some(head)))(
+            (causes, cause) => causes ++ Interruption(Some(cause))
+          )
+      }
+
+    final case class Checked[E](value: E)                   extends Cause[E]
+    final case class Unchecked(value: Throwable)            extends Cause[Nothing]
+    final case class Interruption(value: Option[Throwable]) extends Cause[Nothing]
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: Change to:

```scala
final case object Interruption extends Cause[Nothing]
```

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 35 above)
Comment (regiskuckaertz) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This is bloody great.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 53]
```diff
@@ -88,12 +88,12 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
...
-    case IO.Tags.Fail =>
-      val io = self.asInstanceOf[IO.Fail[E]]
+    case IO.Tags.Terminate =>
+      val io = self.asInstanceOf[IO.Terminate[E]]
 
-      new IO.Fail(f(io.error), io.defects)
+      new IO.Terminate(io.cause.map(f))
 
-    case _ => new IO.Redeem(self, (e: E) => new IO.Fail(f(e), Nil), (a: A) => new IO.Strict(g(a)))
+    case _ => new IO.Redeem(self, (cause: Cause[E]) => new IO.Terminate(cause.map(f)), (a: A) => new IO.Strict(g(a)))
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: This logic for short-circuiting is going to become more tricky. I'd replace all of this with:

```scala
bimap(f, g) = self.redeemPure(f, g)
```

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 54]
```diff
@@ -809,7 +797,7 @@ object IO extends Serializable {
     override def tag = Tags.Supervise
   }
 
-  final class Terminate private[IO] (val causes: List[Throwable]) extends IO[Nothing, Nothing] {
+  final class Terminate[E] private[IO] (val cause: Cause[E]) extends IO[E, Nothing] {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: I would rename `Terminate` to `Fail`.

File: core/shared/src/main/scala/scalaz/zio/Promise.scala [hunk 55]
```diff
@@ -90,7 +89,7 @@ class Promise[E, A] private (private val state: AtomicReference[State[E, A]]) ex
    * Interrupts the promise with the specified list of throwable(s). This will interrupt
    * all fibers waiting on the value of the promise.
    */
-  final def interrupt0(ts: List[Throwable]): IO[Nothing, Boolean] = done(ExitResult.Terminated[E, A](ts))
+  final def interrupt0(ts: List[Throwable]): IO[Nothing, Boolean] = done(ExitResult.interrupted(ts))
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/Promise.scala]: There is only need for 1 interrupt method:

```scala
def interrupt: IO[Nothing, Boolean]
```

i.e. we can get rid of the list of throwables.

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 56]
```diff
@@ -9,56 +11,192 @@ package scalaz.zio
...
+
+    final def fold[Z](z: Z)(f: PartialFunction[(Z, Cause[E]), Z]): Z =
+      (f.lift(z -> self).getOrElse(z), self) match {
+        case (z, Then(left, right)) => right.fold(left.fold(z)(f))(f)
+        case (z, Both(left, right)) => right.fold(left.fold(z)(f))(f)
+
+        case (z, _) => z
+      }
+
+    final def toThrowable: Throwable = FiberFailure(self)
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: I think this can be deleted. It's just a proxy now to `FiberFailure`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 28 above)
Comment (ghostdogpr) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: How about `Fork`? It takes a `handler: Option[List[Throwable] => IO[Nothing, Unit]]`, should it be `Cause[Nothing]` instead?

**Comment by jdegoes** [comment]
Yes, it should be Cause[Nothing] as well.

File: core/shared/src/main/scala/scalaz/zio/IO.scala (hunk 53 above)
Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: `redeemPure` needs `f` and `g` to produce the same type, but here in `bimap` they produce different types.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 57]
```diff
@@ -554,25 +477,34 @@ private object RTS {
...
-                      curIo = null
-                      result = ExitResult.Terminated(allCauses)
+                        val cause = if (status.get.interrupted) io.cause ++ Cause.interrupted else io.cause
+                        result = ExitResult.failed(cause)
+                      } else {
+                        // We have finalizers to run. We'll resume executing with the
+                        // uncaught failure after we have executed all the finalizers:
+                        val completer = io
+                        curIo = doNotInterrupt(finalizer).flatMap(
+                          cause => IO.fail0(cause.fold(completer.cause)(completer.cause ++ _))
```
Comment (regiskuckaertz) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: even shorter: `cause.foldLeft(completer.value)(_ ++ _)`

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 58]
```diff
@@ -554,25 +477,34 @@ private object RTS {
...
-                      // Must run finalizers first before failing:
-                      val finalization = finalizer.flatMap(accumFailures)
-                      val completer    = io
-
-                      curIo = doNotInterrupt(finalization) *> completer
+                      // Error caught:
+                      if (finalizer eq null) {
+                        curIo = nextInstr[E](io.cause, stack)
+                      } else {
+                        curIo = doNotInterrupt(finalizer).map(cause => cause.fold(io.cause)(io.cause ++ _))
```
Comment (regiskuckaertz) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Same here 🤗

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 59]
```diff
@@ -996,40 +894,35 @@ private object RTS {
...
+    def interrupted: Boolean
 
-    /** errors resulting from exceptions thrown during the execution of the fiber */
-    def defects: List[Throwable]
   }
   object FiberStatus extends Serializable {
     final case class Executing[E, A](
-      terminationCauses: Option[List[Throwable]],
-      defects: List[Throwable],
+      interrupted: Boolean,
```
Comment (regiskuckaertz) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Am I correct to say that this reduces the memory footprint of a approximately fiber by half?

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 60]
```diff
@@ -9,56 +11,175 @@ package scalaz.zio
...
+
+    final def fold[Z](z: Z)(f: PartialFunction[(Z, Cause[E]), Z]): Z =
+      (f.lift(z -> self).getOrElse(z), self) match {
+        case (z, Then(left, right)) => right.fold(left.fold(z)(f))(f)
+        case (z, Both(left, right)) => right.fold(left.fold(z)(f))(f)
+
+        case (z, _) => z
+      }
+
+    final def checkedOrRefail: Either[E, Cause[Nothing]] = self.checked.headOption match {
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: `toEither` would work too, but this is just my personal taste.

File: core/shared/src/main/scala/scalaz/zio/RefM.scala [hunk 61]
```diff
@@ -70,12 +70,15 @@ object RefM extends Serializable {
...
-            case Left(ts) => onDefect(ts)
-            case Right(n) => n
-          }, {
-            case (b, a) => ref.set(a) <* promise.complete(b)
-          })
+          update(a).sandboxed.redeem(
+            cause =>
+              cause.unchecked match {
+                case Nil     => IO.unit
+                case defects => onDefect(defects)
```
Comment (regiskuckaertz) [inline core/shared/src/main/scala/scalaz/zio/RefM.scala]: Can `onDefect` become a `Cause[E] => IO[Nothing, Unit]`? Then this becomes `cause.fold(IO.unit, onDefect)` if I see this correctly.

Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/RefM.scala]: The other call to `onDefect` (a few lines up) is based on the result of `onTermination` which also take `List[Throwable] => IO[Nothing, Unit]`. I guess those two should be aligned?

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/RefM.scala]: Oh yeah good spot, specifically `Cause[Nothing]`!

Comment (regiskuckaertz) [reply core/shared/src/main/scala/scalaz/zio/RefM.scala]: In fact, `onTermination` is the only remaining occurrence of `List[Throwable]` in `IO` 🎉

Comment (ghostdogpr) [reply core/shared/src/main/scala/scalaz/zio/RefM.scala]: Haha, just checked the same thing ;)

**Comment by regiskuckaertz** [comment]
I'll let @jdegoes give final approval, to me this looks like a beautiful piece of work 😍

File: core/shared/src/main/scala/scalaz/zio/ExitResult.scala [hunk 62]
```diff
@@ -9,56 +11,175 @@ package scalaz.zio
...
+      case Some(error) => Left(error)
+      case None        => Right(self.asInstanceOf[Cause[Nothing]]) // no E inside this cause, can safely cast
+    }
   }
 
-  private final def combine(ts: List[Throwable], r: ExitResult[_, _]) = r match {
-    case ExitResult.Failed(_, ts2)  => ts ++ ts2
-    case ExitResult.Terminated(ts2) => ts ++ ts2
-    case _                          => ts
+  object Cause {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/ExitResult.scala]: `extends Serializable`

File: core/shared/src/main/scala/scalaz/zio/Errors.scala [hunk 63]
```diff
@@ -1,10 +1,18 @@
 // Copyright (C) 2017-2018 John A. De Goes. All rights reserved.
 package scalaz.zio
+import scalaz.zio.ExitResult.Cause
 
 object Errors {
 
-  final case class UnhandledError(error: Any, defects: List[Throwable] = Nil)
-      extends Exception("An error was not handled by a fiber: " + error.toString())
+  final case class FiberFailure(cause: Cause[Any]) extends Throwable {
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/Errors.scala]: At this point, there's no need for `Errors` object to exist. I'd promote `FiberFailure` to the top level, and rename the file from `Errors.scala` to `FiberFailure.scala`.

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 64]
```diff
@@ -91,9 +91,9 @@ sealed abstract class IO[+E, +A] extends Serializable { self =>
     case IO.Tags.Fail =>
       val io = self.asInstanceOf[IO.Fail[E]]
 
-      new IO.Fail(f(io.error), io.defects)
+      new IO.Fail(io.cause.map(f))
 
-    case _ => new IO.Redeem(self, (e: E) => new IO.Fail(f(e), Nil), (a: A) => new IO.Strict(g(a)))
+    case _ => new IO.Redeem(self, (cause: Cause[E]) => IO.fail0(cause.map(f)), (a: A) => new IO.Strict(g(a)))
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: `bimap` can be expressed as `leftMap(f).map(g)`, then we don't have to worry if this logic is correct.

Comment (jdegoes) [reply core/shared/src/main/scala/scalaz/zio/IO.scala]: Also you'll delete like 15 lines of code. 😄

File: core/shared/src/main/scala/scalaz/zio/IO.scala [hunk 65]
```diff
@@ -740,10 +733,9 @@ object IO extends Serializable {
     final val Uninterruptible = 10
     final val Sleep           = 11
     final val Supervise       = 12
-    final val Terminate       = 13
-    final val Supervisor      = 14
-    final val Ensuring        = 15
-    final val Descriptor      = 16
+    final val Supervisor      = 13
+    final val Ensuring        = 14
+    final val Descriptor      = 15
```
Comment (jdegoes) [inline core/shared/src/main/scala/scalaz/zio/IO.scala]: 😍

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 66]
```diff
@@ -52,8 +47,8 @@ trait RTS {
    * The default handler for unhandled exceptions in the main fiber, and any
    * fibers it forks that recursively inherit the handler.
    */
-  def defaultHandler: List[Throwable] => IO[Nothing, Unit] =
-    (ts: List[Throwable]) => IO.sync(ts.foreach(_.printStackTrace()))
+  def defaultHandler: Cause[Nothing] => IO[Nothing, Unit] =
+    (cause: Cause[Nothing]) => IO.sync(cause.unchecked.foreach(_.printStackTrace()))
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: I think the type may be wrong here. If a fiber doesn't handle a checked `E`, it will end up here. So this should really be `Cause[Any]`.

Also, to print out a message, I'd use `FiberFailure(cause).message`. This way you can take advantage of the work done there to render the cause. Plus that way, you won't miss an `E` if it happens to be inside the `Cause`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 67]
```diff
@@ -79,7 +74,7 @@ trait RTS {
    */
   val YieldMaxOpCount = 1024
 
-  private final def newFiberContext[E, A](handler: List[Throwable] => IO[Nothing, Unit]): FiberContext[E, A] = {
+  private final def newFiberContext[E, A](handler: Cause[Nothing] => IO[Nothing, Unit]): FiberContext[E, A] = {
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Again, I think the handlers will have `Cause[Any] => IO[Nothing, Unit]` as their type.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 68]
```diff
@@ -169,10 +164,10 @@ private object RTS {
   /**
    * An implementation of Fiber that maintains context necessary for evaluation.
    */
-  final class FiberContext[E, A](rts: RTS, val fiberId: FiberId, val unhandled: List[Throwable] => IO[Nothing, Unit])
+  final class FiberContext[E, A](rts: RTS, val fiberId: FiberId, val unhandled: Cause[Nothing] => IO[Nothing, Unit])
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Ditto.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 69]
```diff
@@ -231,33 +226,26 @@ private object RTS {
...
       // finalizers.
       while ((errorHandler eq null) && !stack.isEmpty) {
         stack.pop() match {
-          case a: IO.Redeem[_, _, _, _] =>
+          case a: IO.Redeem[_, _, _, _] if catchError =>
             errorHandler = a.err.asInstanceOf[Any => IO[Any, Any]]
           case f0: Finalizer =>
-            val f: IO[Nothing, Option[List[Throwable]]] = fork(f0.finalizer, _ => IO.unit).observe.map(collectDefect)
+            val f: IO[Nothing, Option[Cause[Nothing]]] =
+              fork(f0.finalizer, _ => IO.unit).observe.map((a: ExitResult[Nothing, Unit]) => a.fold(_ => None, Some(_)))
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Worth adding a `cause: Option[Cause[E]]` onto `ExitResult`, so you can write this line as:

```scala
fork(f0.finalizer, _ => IO.unit).observe.map(_.cause)
```

Further, I'm not sure why the finalizer is being forked. It's probably a holdover from when we needed to do that in order to capture all failures. There's a better way to write that now:

```scala
f0.finalizer.sandbox.redeemPure[Option[Cause[Nothing]]](Some(_), None)
```

This will have the wonderful benefit of making all finalizers synchronous. 🎉 🕺 

@regiskuckaertz See any problems with this?

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 70]
```diff
@@ -273,37 +261,12 @@ private object RTS {
...
-      finalizer
-    }
-
-    private final def zipFailures(ts1: Option[List[Throwable]], ts2: Option[List[Throwable]]): Option[List[Throwable]] =
-      (ts1, ts2) match {
-        case (Some(ts1), Some(ts2)) => Some(ts1 ++ ts2)
-        case (ts @ Some(_), None)   => ts
-        case (None, ts @ Some(_))   => ts
-        case (None, None)           => None
+    private final def zipCauses(c1: Option[Cause[Nothing]], c2: Option[Cause[Nothing]]): Option[Cause[Nothing]] =
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]:
```scala
c1.flatMap(c1 => c2.map(c1 ++ _)).orElse(c1).orElse(c2)
```

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 71]
```diff
@@ -554,25 +477,34 @@ private object RTS {
                     curIo = enterSupervision *>
                       io.value.ensuring(exitSupervision(io.supervisor))
 
-                  case IO.Tags.Terminate =>
-                    val io = curIo.asInstanceOf[IO.Terminate]
+                  case IO.Tags.Fail =>
+                    val io = curIo.asInstanceOf[IO.Fail[E]]
 
-                    val finalizer = interruptStack
+                    val finalizer = unwindStack(io.cause.isChecked)
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Right now it's only catching the exception if the cause is checked. I'm not sure that's correct because `Redeem` now—quite intentionally—lets us "catch" unchecked and interruption. We are not using that, I don't think, but if we're doing the correct thing in "lifting" the old methods (redeem, etc.), up into `Redeem`, then we won't need this logic here. So I _think_ you want to delete the boolean to `interruptStack` and always let the catcher catch the exception.

In a later pull request, I'll add some "hints" that let us know when the cause will be caught and used, versus caught and then rethrown. This will be strictly for performance, though, and will not be required for correctness.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 72]
```diff
@@ -554,25 +477,34 @@ private object RTS {
...
+                        curIo = null
 
-                      curIo = null
-                      result = ExitResult.Terminated(allCauses)
+                        val cause = if (status.get.interrupted) io.cause ++ Cause.interrupted else io.cause
+                        result = ExitResult.failed(cause)
+                      } else {
+                        // We have finalizers to run. We'll resume executing with the
+                        // uncaught failure after we have executed all the finalizers:
+                        val completer = io
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Because `io` is already a local val, you can inline it into the subsequent line, rather than using `completer`.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 73]
```diff
@@ -554,25 +477,34 @@ private object RTS {
...
+                        )
+                      }
                     } else {
-                      // Must run finalizers first before failing:
-                      val finalization = finalizer.flatMap(accumFailures)
-                      val completer    = io
-
-                      curIo = doNotInterrupt(finalization) *> completer
+                      // Error caught:
+                      if (finalizer eq null) {
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This logic is 10x better than the old logic!

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala [hunk 74]
```diff
@@ -928,11 +826,11 @@ private object RTS {
                 try cancel()
                 catch {
                   case t: Throwable if (rts.nonFatal(t)) =>
-                    fork(unhandled(t :: Nil), unhandled)
+                    fork(IO.terminate(t), unhandled)
```
Comment (jdegoes) [inline core/jvm/src/main/scala/scalaz/zio/RTS.scala]: This is a change from the old version. I _think_ it will have the same effect. /cc @regiskuckaertz

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 59 above)
Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Of the `FiberStatus`, yes (although not quite half), although the `FiberContext` has other crap (stack, etc.).

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 69 above)
Comment (regiskuckaertz) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Nope, haha that's perfect 💯

Comment (kaishh) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Note, this PR does not change the run/sandbox encoding yet.

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 74 above)
Comment (regiskuckaertz) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Hmm, I don't think so. This will evaluate in `IO.Tags.Fail` with no finalizer, meaning it will just produce `ExitResult.Failed(Cause.unchecked(t))`, whereas `unhandled(Cause.unchecked(t))` will evaluate the supervision.

Comment (regiskuckaertz) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Ooh, but the result is evaluated in `reportErrors`! So yes, that;s the same 😄

Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Maybe we should revert just in case. 😄

**Comment by ghostdogpr** [comment]
@jdegoes I applied all the changes except https://github.com/scalaz/scalaz-zio/pull/342#discussion_r231938103 (remove `fork`) which breaks the tests

File: core/jvm/src/main/scala/scalaz/zio/RTS.scala (hunk 69 above)
Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Can you try implementing #360? It will just be a couple lines and may fix whatever issue is causing the failures.

Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: /cc @ghostdogpr

Comment (ghostdogpr) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: I implemented `run` and it fixed the issue indeed!
Looking at `raceWith` now before I commit all.

Comment (jdegoes) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Don’t worry about that one, it is more involved and we can fix it in that ticket.

Comment (ghostdogpr) [reply core/jvm/src/main/scala/scalaz/zio/RTS.scala]: Okay!

**Comment by ghostdogpr** [comment]
@jdegoes all pushed and tests passing 👌

**Comment by regiskuckaertz** [comment]
What a marathon it was 🏃‍♂️

**Comment by jdegoes** [comment]
Merged! Thanks again to @ghostdogpr and @regiskuckaertz for all your work on this!

giphy
